### ISSUE TITLE
The SGE Option

### ISSUE THREAD

**Issue by chenshixuan** [Nextomics/NextDenovo#1]
Hi,hujiang:
     The SGE parameter is not so fit to my SGE  system .On my SGE, We must echo the Project name ,vf,and cpu number,the job will be submitted.I found that ,your mode is like falcon,so could you add some parameters  like falcon?
job_queue = all.q
sge_option_da = -P 1234 -l vf=18G -q %(job_queue)s -l num_proc=4  
sge_option_la = -P 1234 l vf=30G -q %(job_queue)s -l num_proc=4  
Thank you !

**Comment by moold** [comment]
Hi, I have fix this.
    Please update NextDenovo and use sge_options = -P 1234  -l vf={vf} -q all.q -l num_proc={cpu} in your config file. Please do not change {vf} and {cpu}, NextDenovo will automatically replace to the required resources for different steps.
