### ISSUE TITLE
read_cuoff = 1k 应为 read_cutoff = 1k 问一下现在的参数设置

### ISSUE THREAD

**Issue by hayliu** [Nextomics/NextDenovo#10]
[General]
job_type = local
job_prefix = nextDenovo
task = all
rewrite = yes # yes/no
input_type = raw
input_fofn = ./input.fofn
workdir = ./01_rundir

[correct_option]
**read_cuoff = 1k**
seed_cutoff = 32k
blocksize = 1g
pa_raw_align = 2
pa_correction = 2
seed_cutfiles = 2
sort_options = -m 50g -t 20 -k 50
minimap2_options = -x ava-ont -t 20
correction_options = -p 40

**Comment by moold** [comment]
Thank you for your suggestion, I will fix it in the next version.
