### ISSUE TITLE
NextDenovo/bin/seq_dump         nanopore.fastq  does not exist!

### ISSUE THREAD

**Issue by li0604** [Nextomics/NextDenovo#105]
Hi, everybody.
I am using the software named nextdenovo for my Nanopore sequencing data assembling. But there is an error and I don't how to solved it. The logfile was presented as following. Would you mind sharing your suggestion about this kind of error?

![image](https://user-images.githubusercontent.com/54136123/110209338-f2f99780-7ec6-11eb-860e-743ab0628920.png)

![)RVV4FE(P8LWB 7G6{DK49D](https://user-images.githubusercontent.com/54136123/110209372-2f2cf800-7ec7-11eb-91df-9e554ad76b49.png)

**Comment by moold** [comment]
1. It seems there is a space after file `...nanopore.fastq` in `input.fofn`, so please delete it.
2. you need set `ava-ont` for `minimap2_options_raw` and `minimap2_options_cns`.
3. your`seed_cutoff` is too short.
See [here](https://nextdenovo.readthedocs.io/en/latest/QSTART.html#limitations) and [here](https://nextdenovo.readthedocs.io/en/latest/OPTION.html) for more details.

**Comment by li0604** [comment]
Thanks for your help and I corrected the reasons 2 and 3. The program is running.
