### ISSUE TITLE
License

### ISSUE THREAD

**Issue by rivera10** [Nextomics/NextDenovo#108]
Hello, 

I just noticed the repository does not include a LICENSE, which means that I cannot use the tool. See [1](https://choosealicense.com/no-permission/) and [2](https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/licensing-a-repository#choosing-the-right-license). Can you add a License to your repository so I am able to fork and use the tool? Thanks in advance.

Best,
Ramon

**Comment by moold** [comment]
Hi, the GPL License has been added.

**Comment by rivera10** [comment]
Thanks!
