### ISSUE TITLE
[ERROR] 2021-03-29 21:33:04,452 seed_cns failed: please check the following logs:

### ISSUE THREAD

**Issue by kuangtianhui** [Nextomics/NextDenovo#110]
**Error message**
[ERROR] 2021-03-29 21:33:04,452 seed_cns failed: please check the following logs:
[ERROR] 2021-03-29 21:33:04,481 /public/home/02.cns_align/01.seed_cns.sh.work/seed_cns31/nextDenovo.sh.e
context of /public/home/02.cns_align/01.seed_cns.sh.work/seed_cns31/nextDenovo.sh.e
hostname
+ hostname
cd /public/home/02.cns_align/01.seed_cns.sh.work/seed_cns31
+ cd /public/home/02.cns_align/01.seed_cns.sh.work/seed_cns31
time /public/home/bin/miniconda3/bin/python /public/home/Software/NextDenovo/lib/nextcorrect.py -f /public/home
+ /public/home/bin/miniconda3/bin/python /public/home/Software/NextDenovo/lib/nextcorrect.py -f /public/home
[INFO] 2021-03-29 22:16:48,546 Corrected step options:
[INFO] 2021-03-29 22:16:48,546 Namespace(blacklist='/public/home/01.raw_align/03.sort_alig
[WARNING] 2021-03-29 22:16:48,591 Skip 31346 seeds in blacklist.
[WARNING] 2021-03-29 22:16:48,671 Skip 6976 corrected seeds.
[INFO] 2021-03-29 22:16:48,891 Start a cns worker in 89889 from parent 89874
[INFO] 2021-03-29 22:16:48,893 Start a cns worker in 89890 from parent 89874
[INFO] 2021-03-29 22:16:48,894 Start a cns worker in 89891 from parent 89874
[INFO] 2021-03-29 22:16:48,895 Start a cns worker in 89892 from parent 89874
[INFO] 2021-03-29 22:16:48,895 Start a cns worker in 89893 from parent 89874
[INFO] 2021-03-29 22:16:48,896 Start a cns worker in 89894 from parent 89874
[INFO] 2021-03-29 22:16:48,897 Start a cns worker in 89895 from parent 89874
[INFO] 2021-03-29 22:16:48,898 Start a cns worker in 89896 from parent 89874
[INFO] 2021-03-29 22:16:48,899 Start a cns worker in 89897 from parent 89874
[INFO] 2021-03-29 22:16:48,899 Start a cns worker in 89898 from parent 89874
[INFO] 2021-03-29 22:16:48,900 Start a cns worker in 89899 from parent 89874
[INFO] 2021-03-29 22:16:48,900 Start a cns worker in 89900 from parent 89874
[INFO] 2021-03-29 22:16:48,901 Start a cns worker in 89901 from parent 89874
[INFO] 2021-03-29 22:16:48,901 Start a cns worker in 89902 from parent 89874
[INFO] 2021-03-29 22:16:48,902 Start a cns worker in 89903 from parent 89874
[INFO] 2021-03-29 22:16:48,902 Start a cns worker in 89904 from parent 89874

real    11m37.995s
user    175m30.946s
sys     3m49.142s
touch /public/home/02.cns_align/01.seed_cns.sh.work/seed_cns31/nextDenovo.sh.done
+ touch /public/home/02.cns_align/01.seed_cns.sh.work/seed_cns31/nextDenovo.sh.done

**Genome characteristics**
`1.8Gb, heterozygous rate, repeat content...`

**Input data**
`98Gb, 28, 14018bp...`

**Config file**
[General]
job_type = local
job_prefix = nextDenovo
task = all # 'all', 'correct', 'assemble'
rewrite = yes # yes/no
deltmp = yes
rerun = 3
parallel_jobs = 40
input_type = raw
read_type = clr
input_fofn = /public/home/input.info
workdir = /public/home
# cluster_options = -l vf={vf} -q all.q -pe smp {cpu} -S {bash} -w n

[correct_option]
read_cutoff = 5k
seed_cutoff = 5126
blocksize = 10g
pa_correction = 40
seed_cutfiles = 40
sort_options = -m 20g -t 16 -k 40
minimap2_options_raw = -x ava-pb -t 16
correction_options = -p 16 -max_lq_length 5

[assemble_option]
random_round = 20
minimap2_options_cns = -x ava-pb -t 16 -k17 -w17
nextgraph_options = -a 1

**Operating system**
CentOS Linux release 7.6.1810 (Core)

**GCC**
8.1.0

**Python**
3+

**NextDenovo**
v2.4.0

There are two warnings, what is impact of  these two warnings ???

**Comment by kuangtianhui** [comment]
I change the parameter “sort_options = -m 40g” to “sort_options = -m 20g” to rerun the program.

**Comment by moold** [comment]
Just ignore the warnings , which do not affect the assembly result. From the log, it seems the subjob `seed_cns31` has been finished without error, because it produced the done file `nextDenovo.sh.done`.

**Comment by kuangtianhui** [comment]
Thank you!!! Yes, the subjob seed_cns31 has been finished without error. I used to think that the program skipped an correction process. However, it seems not. So, thank you for clearing my mind!
