### ISSUE TITLE
Error in line 856, line 568 and line 8

### ISSUE THREAD

**Issue by anacatalan** [Nextomics/NextDenovo#116]
**Describe the bug**
I am trying to run nextDenovo from our slurm cluster.

**Error message**
Traceback (most recent call last):
  File "/dss/dsslegfs02/pn73se/pn73se-dss-0000/spack/opt/linux-sles15-skylake_avx512/nextdenovo/2.4.0-gcc-8.4.0-54uzind/bin/nextDenovo", line 856, in <module>
    main(args)
  File "/dss/dsslegfs02/pn73se/pn73se-dss-0000/spack/opt/linux-sles15-skylake_avx512/nextdenovo/2.4.0-gcc-8.4.0-54uzind/bin/nextDenovo", line 568, in main
    from task_control import Task, Run
  File "/dss/dsslegfs02/pn73se/pn73se-dss-0000/spack/opt/linux-sles15-skylake_avx512/nextdenovo/2.4.0-gcc-8.4.0-54uzind/lib/task_control.py", line 8, in <module>
    import psutil
ModuleNotFoundError: No module named 'psutil'

**Genome characteristics**
Genome size: 759mb. No information on repeats and heterozygosity 

**Input data**
I need to get this info first

**Config file**
# Config file for LaNoc
#[General]
job_type = slurm
job_prefix = nextDenovo_LaNoc
task = all
rewrite = yes
deltmp = yes
parallel_jobs = 20
input_type = raw
read_type = ont # clr, ont, hifi
input_fofn = input_LaNoc.fofn
workdir = 01_rundir
usetempdir= temp
cluster_options= auto
nodelist= biohpc_gen_highmem
#[correct_option]
read_cutoff = 1k
genome_size = 760m # estimated genome size
sort_options = -m 100g -t 30
minimap2_options_raw = -t 8
pa_correction = 3
correction_options = -p 15

#[assemble_option]
minimap2_options_cns = -t 8
nextgraph_options = -a 1

**Operating system**
I am using slurm
You can use the command `lsb_release -a` to get it. --> no I can't

**GCC**
What version of GCC are you using?
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib64/gcc/x86_64-suse-linux/7/lto-wrapper
OFFLOAD_TARGET_NAMES=hsa:nvptx-none
Target: x86_64-suse-linux
Configured with: ../configure --prefix=/usr --infodir=/usr/share/info --mandir=/usr/share/man --libdir=/usr/lib64 --libexecdir=/usr/lib64 --enable-languages=c,c++,objc,fortran,obj-c++,ada,go --enable-offload-targets=hsa,nvptx-none=/usr/nvptx-none, --without-cuda-driver --enable-checking=release --disable-werror --with-gxx-include-dir=/usr/include/c++/7 --enable-ssp --disable-libssp --disable-libvtv --disable-libcc1 --disable-plugin --with-bugurl=https://bugs.opensuse.org/ --with-pkgversion='SUSE Linux' --with-slibdir=/lib64 --with-system-zlib --enable-libstdcxx-allocator=new --disable-libstdcxx-pch --enable-version-specific-runtime-libs --with-gcc-major-version-only --enable-linker-build-id --enable-linux-futex --enable-gnu-indirect-function --program-suffix=-7 --without-system-libunwind --enable-multilib --with-arch-32=x86-64 --with-tune=generic --build=x86_64-suse-linux --host=x86_64-suse-linux
Thread model: posix
gcc version 7.5.0 (SUSE Linux) 

**Python**
Python 3.7.10

**NextDenovo**
nextdenovo/2.4.0

**To Reproduce** (Optional)
Steps to reproduce the behavior. Providing a minimal test dataset on which we can reproduce the behavior will generally lead to quicker turnaround time!

**Additional context** (Optional)

**Comment by moold** [comment]
As the log says, your system do not have `psutil` module, so try to install it first by `pip install psutil`

**Comment by DaniPaulo** [comment]
Hi @anacatalan,
I'm also trying to figure out how to run NextDenovo in a HPC environment using SLURM. 
Would you be able to share your `script.slurm.sh` with me?
