### ISSUE TITLE
Problem: ValueError: zero length field name in format

### ISSUE THREAD

**Issue by li081766** [Nextomics/NextDenovo#12]
Hi, 

Once I run nextdenovo, I met the problem "ValueError: zero length field name in format". 
Traceback (most recent call last):
  File "../nextDenovo", line 394, in <module>
    main(args)
  File "../nextDenovo", line 278, in main
    task.set_subtasks(job_prefix = job_prefix)
  File "../NextDenovo/lib/taskControl.py", line 128, in set_subtasks
    subtask_dir = self.prefix + '{:0>{}}'.format(i, len(str(task_count)))
ValueError: zero length field name in format

Could you help me with the problem?
Thank you!

**Comment by moold** [comment]
Could you provide the config file?

**Comment by li0817696** [comment]
The config file:
[General]
job_type = local
job_prefix = Chequ
task = all
rewrite = yes # yes/no
deltmp =  yes
#rerun = 3
#parallel_jobs = 50
input_type = raw
input_fofn = ./input.fofn
workdir = ./nextDenovo
#cluster_options = -l vf={vf} -q af.q -l num_proc={cpu} 

[correct_option]
read_cuoff = 1k
seed_cutoff = 25k
blocksize = 1g
pa_raw_align = 5
pa_correction = 15
seed_cutfiles = 10
sort_options = -m 5g -t 2 -k 50
minimap2_options = -x ava-ont -t 8
correction_options = -p 15

**Comment by li0817696** [comment]
the config file:
[General]
job_type = local
job_prefix = test
task = all
rewrite = yes # yes/no
deltmp =  yes
#rerun = 3
#parallel_jobs = 50
input_type = raw
input_fofn = ./input.fofn
workdir =./nextDenovo


[correct_option]
read_cuoff = 1k
seed_cutoff = 25k
blocksize = 1g
pa_raw_align = 5
pa_correction = 15
seed_cutfiles = 10
sort_options = -m 5g -t 2 -k 50
minimap2_options = -x ava-ont -t 8
correction_options = -p 15

**Comment by moold** [comment]
What is your Python version? Currently, NextDenovo is only support python2.7.

**Comment by li081766** [comment]
Thanks for your suggestion. I will try again.
