### ISSUE TITLE
How to get the assembly greater then 3.5Gb?

### ISSUE THREAD

**Issue by Ural-Yunusbaev** [Nextomics/NextDenovo#121]
**Question or Expected behavior**
A clear and concise description of your question or what you expected to happen.

**Operating system**
Which operating system and version are you using?
You can use the command `lsb_release -a` to get it.

**GCC**
What version of GCC are you using?
You can use the command `gcc -v` to get it.

**Python**
What version of Python are you using?
You can use the command `python --version` to get it.

**NextDenovo**
What version of NextDenovo are you using?
You can use the command `nextDenovo -v` to get it.

**Additional context** (Optional)

**Comment by Ural-Yunusbaev** [comment]
Hey there!
I am working with a genome larger than 16Gb. ND assembles only 3.5Gb. Is it possible to somehow make ND go to 17Gb?
Thanks,
Ural

**Comment by moold** [comment]
The released version does not support assembly for genome size > 3.5GB. You can try to use wtdbg, smrtdenovo, miniasm, fly or other tools to assemble with corrected reads generated by NextDenovo , which usually produce a better result than using raw reads.
