### ISSUE TITLE
error on slurm system

### ISSUE THREAD

**Issue by zskey-zn** [Nextomics/NextDenovo#127]
**Describe the bug**
Hi, I run nextdenovo(2.4.0) on slurm sysytem, but it can't work Successfully.I have downloaded  these package.
<pre>
cmd>module load  nextdenovo/2.4.0
Loading nextdenovo/2.4.0
  Loading requirement: python/3.7.10 drmaa/1.1.2
</pre>
**Error message**
<pre>
python3: error: s_p_parse_file: unable to status file /usr/local/etc/slurm.conf: No such file or directory, retrying in 1sec up to 60sec
python3: error: ClusterName needs to be specified
python3: error: Unable to establish controller machine
Traceback (most recent call last):
  File "/public/frasergen/PUB/software/nextdenovo/NextDenovo-2.4.0/nextDenovo", line 856, in <module>
    main(args)
  File "/public/frasergen/PUB/software/nextdenovo/NextDenovo-2.4.0/nextDenovo", line 598, in main
    task.run.start()
  File "/public/frasergen/PUB/software/nextdenovo/NextDenovo-2.4.0/lib/task_control.py", line 187, in start
    self._sge()
  File "/public/frasergen/PUB/software/nextdenovo/NextDenovo-2.4.0/lib/task_control.py", line 241, in _sge
    jobid = self.drmaa.runJob(jt)
  File "/public/frasergen/PUB/software/python/Python-3.7.10/lib/python3.7/site-packages/drmaa/session.py", line 314, in runJob
    c(drmaa_run_job, jid, sizeof(jid), jobTemplate)
  File "/public/frasergen/PUB/software/python/Python-3.7.10/lib/python3.7/site-packages/drmaa/helpers.py", line 302, in c
    return f(*(args + (error_buffer, sizeof(error_buffer))))
  File "/public/frasergen/PUB/software/python/Python-3.7.10/lib/python3.7/site-packages/drmaa/errors.py", line 151, in error_check
    raise _ERRORS[code - 1](error_string)
drmaa.errors.InternalException: code 1: slurm_submit_batch_job error (2): No such file or directory
</pre>

**my cfg file**
<pre>
[General]
job_type = slurm
job_prefix = nextDenovo
task = all # 'all', 'correct', 'assemble'
rewrite = yes # yes/no
deltmp = yes
rerun = 3
parallel_jobs = 2
input_type = raw
read_type = clr
input_fofn = input.fofn
workdir = ./01_rundir
cluster_options =  --cpus-per-task={cpu} --mem-per-cpu={vf}

[correct_option]
read_cutoff = 1k
genome_size = 308161
pa_correction = 2
sort_options = -m 1g -t 2
minimap2_options_raw =  -t 8
correction_options = -p 15

[assemble_option]
minimap2_options_cns =  -t 8
nextgraph_options = -a 1
</pre>

how to dedug this problem?

**Comment by zskey-zn** [comment]
I suppose the problem in this.
<pre>
export SLURM_ROOT=/opt/gridview/slurm
export SLURM_CELL=default
</pre>

in SGE:
the correct code is
<pre>
export SGE_ROOT=/opt/sge
export SGE_CELL=default
</pre>


so, when I run the nextdenovo code in slurm, how to set "root" and "cell" in my code?

**Comment by moold** [comment]
Try the latest version, which does not require `drmaa`.

**Comment by zskey-zn** [comment]
Hi,&nbsp;


thanks, I will try it soon.


Best wish for you!


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Nextomics/NextDenovo"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年10月13日(星期三) 中午1:36
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Nextomics/NextDenovo] error on slurm system (#127)





 
Try the latest version, which does not require drmaa.
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
