### ISSUE TITLE
srun: error

### ISSUE THREAD

**Issue by fengyuanli304** [Nextomics/NextDenovo#128]
Hi, Dr. Hu
I try to assemble the genome of some species using NextDenovo, but one of them has an error. Thank you very much.
**Question or Expected behavior**
srun: error: Node failure on cn09.

**Operating system**
Which operating system and version are you using?
CentOS Linux release 7.5.1804 (Core).

**GCC**
What version of GCC are you using?
gcc version 4.8.5 20150623 (Red Hat 4.8.5-28) (GCC)

**Python**
What version of Python are you using?
python 2.7.15

**NextDenovo**
What version of NextDenovo are you using?
nextDenovo 2.3.1

**Additional context** (Optional)
run.cfg:
[General]
job_type = local
job_prefix = nextDenovo2.3.1
task = all # 'all', 'correct', 'assemble'
rewrite = yes # yes/no
deltmp = yes
rerun = 3
parallel_jobs = 4
input_type = raw
input_fofn = ./input.fofn
workdir = ./

[correct_option]
read_cutoff = 1k
seed_cutoff = 25k
genome_size = 900m
blocksize = 1g
pa_correction = 4
seed_cutfiles = 4
sort_options = -m 25g -t 5 -k 50
minimap2_options_raw = -x ava-ont -t 5
correction_options = -p 5

[assemble_option]
minimap2_options_cns = -x ava-ont -t 5 -k17 -w17
nextgraph_options = -a 1

log:
[INFO] 2021-09-14 15:29:12,162 start...
[INFO] 2021-09-14 15:29:12,163 logfile: pid17926.log.info
[WARNING] 2021-09-14 15:29:12,167 Re-write workdir
[INFO] 2021-09-14 15:29:12,167 options: 
[INFO] 2021-09-14 15:29:12,167 {'sort_threads': 5, 'nodelist': '', 'rewrite': 1, 'blocksize': '1g', 'job_prefix': 'nextDenovo2.3.1', 'job_type': 'local', 'minimap2_options_map': ' -x map-ont', 'cns_threads': 5, 'map_threads': 5, 'sort_mem': '25g', 'seed_cutoff': '25000', 'input_fofn': '/gpfs/user/lifengyuan/data/nextdenovo_ot4/./input.fofn', 'read_cutoff': '1k', 'input_type': 'raw', 'sort_options': '-m 25g -t 5 -k 50', 'parallel_jobs': '4', 'cluster_options': '', 'sge_queue': '', 'ctg_graphdir': '/gpfs/user/lifengyuan/data/nextdenovo_ot4/.//03.ctg_graph', 'pa_correction': '4', 'genome_size': '900m', 'workdir': '/gpfs/user/lifengyuan/data/nextdenovo_ot4/./', 'minimap2_threads': (5, 5), 'minimap2_options_raw': '-x ava-ont -t 5', 'minimap2_options_cns': '-x ava-ont -t 5 -k17 -w17 --minlen 2000 --maxhan1 5000', 'cns_aligndir': '/gpfs/user/lifengyuan/data/nextdenovo_ot4/.//02.cns_align', 'seed_cutfiles': '4', 'raw_aligndir': '/gpfs/user/lifengyuan/data/nextdenovo_ot4/.//01.raw_align', 'task': 'all', 'ctg_cns_options': ' -p 5', 'deltmp': 1, '_random_round_with_less_accuracy': 0, 'rerun': 3, 'correction_options': '-p 5 -max_lq_length 10000 -min_len_seed 12500', 'nextgraph_options': '-a 1'}
[INFO] 2021-09-14 15:29:12,167 skip mkdir: /gpfs/user/lifengyuan/data/nextdenovo_ot4/./
[INFO] 2021-09-14 15:29:12,168 mkdir: /gpfs/user/lifengyuan/data/nextdenovo_ot4/.//01.raw_align
[INFO] 2021-09-14 15:29:12,168 mkdir: /gpfs/user/lifengyuan/data/nextdenovo_ot4/.//02.cns_align
[INFO] 2021-09-14 15:29:12,169 mkdir: /gpfs/user/lifengyuan/data/nextdenovo_ot4/.//03.ctg_graph
[INFO] 2021-09-14 15:29:12,170 analysis tasks done
[INFO] 2021-09-14 15:29:17,184 total jobs: 1
[INFO] 2021-09-14 15:29:17,186 Throw jobID:[17941] jobCmd:[/gpfs/user/lifengyuan/data/nextdenovo_ot4/01.raw_align/01.db_split.sh.work/db_split0/nextDenovo2.3.1.sh] in the local_cycle.
[INFO] 2021-09-14 15:52:24,926 db_split done
[INFO] 2021-09-14 15:52:24,936 analysis tasks done
[INFO] 2021-09-14 15:52:25,070 total jobs: 206
[INFO] 2021-09-14 15:52:25,071 Throw jobID:[19300] jobCmd:[/gpfs/user/lifengyuan/data/nextdenovo_ot4/01.raw_align/02.raw_align.sh.work/raw_align000/nextDenovo2.3.1.sh] in the local_cycle.
[INFO] 2021-09-14 15:52:25,573 Throw jobID:[19305] jobCmd:[/gpfs/user/lifengyuan/data/nextdenovo_ot4/01.raw_align/02.raw_align.sh.work/raw_align001/nextDenovo2.3.1.sh] in the local_cycle.
[INFO] 2021-09-14 15:52:26,076 Throw jobID:[19311] jobCmd:[/gpfs/user/lifengyuan/data/nextdenovo_ot4/01.raw_align/02.raw_align.sh.work/raw_align002/nextDenovo2.3.1.sh] in the local_cycle.
[INFO] 2021-09-14 15:52:26,579 Throw jobID:[19322] jobCmd:[/gpfs/user/lifengyuan/data/nextdenovo_ot4/01.raw_align/02.raw_align.sh.work/raw_align003/nextDenovo2.3.1.sh] in the local_cycle.
[INFO] 2021-09-14 16:25:05,782 Throw jobID:[21371] jobCmd:[/gpfs/user/lifengyuan/data/nextdenovo_ot4/01.raw_align/02.raw_align.sh.work/raw_align004/nextDenovo2.3.1.sh] in the local_cycle.
[INFO] 2021-09-14 16:26:43,537 Throw jobID:[21480] jobCmd:[/gpfs/user/lifengyuan/data/nextdenovo_ot4/01.raw_align/02.raw_align.sh.work/raw_align005/nextDenovo2.3.1.sh] in the local_cycle.
[INFO] 2021-09-14 16:28:10,917 Throw jobID:[21591] jobCmd:[/gpfs/user/lifengyuan/data/nextdenovo_ot4/01.raw_align/02.raw_align.sh.work/raw_align006/nextDenovo2.3.1.sh] in the local_cycle.
[INFO] 2021-09-14 16:29:22,816 Throw jobID:[21678] jobCmd:[/gpfs/user/lifengyuan/data/nextdenovo_ot4/01.raw_align/02.raw_align.sh.work/raw_align007/nextDenovo2.3.1.sh] in the local_cycle.
[INFO] 2021-09-14 16:29:23,636 Throw jobID:[21684] jobCmd:[/gpfs/user/lifengyuan/data/nextdenovo_ot4/01.raw_align/02.raw_align.sh.work/raw_align008/nextDenovo2.3.1.sh] in the local_cycle.
srun: error: Node failure on cn09
srun: error: Node failure on cn09

/01.raw_align/02.raw_align.sh.work/raw_align008/nextDenovo2.3.1.sh.e
hostname
+ hostname
cd /gpfs/user/lifengyuan/data/nextdenovo_ot4/01.raw_align/02.raw_align.sh.work/raw_align008
+ cd /gpfs/user/lifengyuan/data/nextdenovo_ot4/01.raw_align/02.raw_align.sh.work/raw_align008
time /gpfs/user/lifengyuan/software/NextDenovo/bin/minimap2-nd --step 1 --dual=yes -x ava-ont -t 5 /gpfs/user/lifengyuan/data/nextdenovo_ot4/.//01.raw_align/input.seed.002.2bit /gpfs/user/lifengyuan/data/nextdenovo_ot4/.//01.raw_align/input.part.046.2bit -o input.seed.002.2bit.8.ovl;
+ /gpfs/user/lifengyuan/software/NextDenovo/bin/minimap2-nd --step 1 --dual=yes -x ava-ont -t 5 /gpfs/user/lifengyuan/data/nextdenovo_ot4/.//01.raw_align/input.seed.002.2bit /gpfs/user/lifengyuan/data/nextdenovo_ot4/.//01.raw_align/input.part.046.2bit -o input.seed.002.2bit.8.ovl

**Comment by moold** [comment]
It seems the error was caused by the computer cluster, so you can update NextDenovo to the latest version and try again.

**Comment by fengyuanli304** [comment]
Hi, Dr. Hu
Thank you for your reply. I update NextDenovo to the latest version and try again. 
I got the same error reported before: srun: error: Node failure on cn01 but nextDenovo2.4.sh.e says insufficient memory
Could I deal with this problem by optimizing parallel computing parameters?

run.cfg:
[General]
job_type = local
job_prefix = nextDenovo2.4
task = all # 'all', 'correct', 'assemble'
rewrite = yes # yes/no
deltmp = yes
parallel_jobs = 4
input_type = raw
read_type = ont
input_fofn = ./input.fofn
workdir = ./

[correct_option]
read_cutoff = 1k
seed_cutoff = 25k
genome_size = 900m
blocksize = 1g
pa_correction = 4
sort_options = -m 25g -t 5
minimap2_options_raw = -t 5
correction_options = -p 5

[assemble_option]
minimap2_options_cns = -t 5
nextgraph_options = -a 1


hostname
+ hostname
cd /gpfs/user/lifengyuan/data/nextdenovo_ot4/01.raw_align/02.raw_align.sh.work/raw_align012
+ cd /gpfs/user/lifengyuan/data/nextdenovo_ot4/01.raw_align/02.raw_align.sh.work/raw_align012
time /gpfs/user/lvweifan/software/NextDenovo/bin/minimap2-nd --step 1 --dual=yes -t 5 -x ava-ont /gpfs/user/lifengyuan/data/nextdenovo_ot4/.//01.raw_align/input.seed.002.2bit /gpfs/user/lifengyuan/data/nextdenovo_ot4/.//01.raw_align/input.part.019.2bit -o input.seed.002.2bit.12.ovl;
+ /gpfs/user/lvweifan/software/NextDenovo/bin/minimap2-nd --step 1 --dual=yes -t 5 -x ava-ont /gpfs/user/lifengyuan/data/nextdenovo_ot4/.//01.raw_align/input.seed.002.2bit /gpfs/user/lifengyuan/data/nextdenovo_ot4/.//01.raw_align/input.part.019.2bit -o input.seed.002.2bit.12.ovl
[M::mm_idx_gen::93.324*1.98] collected minimizers
[M::mm_idx_gen::117.858*2.58] sorted minimizers
[M::main::117.858*2.58] loaded/built the index for 108422 target sequence(s)
[M::mm_mapopt_update::121.889*2.53] mid_occ = 1414
[M::mm_idx_stat] kmer size: 15; skip: 5; is_hpc: 0; #seq: 108422
[M::mm_idx_stat::124.019*2.50] distinct minimizers: 184340220 (39.10% are singletons); average occurrences: 7.429; average spacing: 2.922
[morecore] insufficient memory

**Comment by moold** [comment]
Yes, see [here](https://nextdenovo.readthedocs.io/en/latest/FAQ.html#how-to-optimize-parallel-computing-parameters)
