### ISSUE TITLE
minimap2 option "-I"

### ISSUE THREAD

**Issue by iggyB** [Nextomics/NextDenovo#13]
Hej,

In **nextDenovo**, lines 165-171 contain hard-coded chunk size -I 3G:
```
			if part_file != seed_file:
				cmd += SCRIPT_PATH + '/bin/minimap2-hack -I 3G --dual=yes ' + cfg['minimap2_options'] + ' ' + seed_file  + ' ' + part_file + \
					' > ' + os.path.basename(seed_file) + '.' +  str(k) + '.ovl;'
				cmd += 'ln -sf ' + os.path.basename(seed_file) + '.' +  str(k) + '.ovl ' + os.path.basename(part_file) + '.' +  str(k) + '.ovl;'
			else:
				cmd += SCRIPT_PATH + '/bin/minimap2-hack -I 3G ' + cfg['minimap2_options'] + ' ' + seed_file  + ' ' + part_file + \
					' > ' + os.path.basename(seed_file) + '.' +  str(k) + '.ovl;'
```

If one adds additional minimap2 options, the command results in two "-I" flags. Not sure how minimap2 interprets such situation.

Is there any reason for 3G chunks, or can it be just removed? 

Cheers,
Iggy

**Comment by moold** [comment]
Yes, you can remove it, but removing it means minimap2 need more memory to do alignment, our test shown setting -I 3G will make minimap2 use about 30-40 Gb memory for a single task with 8 threads.

**Comment by moold** [comment]
If you add additional minimap2 options, the command results in two "-I" flags.  This is no problem, and the later will overwrite the first one.

**Comment by iggyB** [comment]
Alright! Sounds good.
