### ISSUE TITLE
Command terminated by signal 9

### ISSUE THREAD

**Issue by kreyszhang** [Nextomics/NextDenovo#135]
**Error message**
I just started learning this software, and I don't quite understand what this error means.
what signal 9 means

full bug report
$more /home/ubuntu/data/result/01_rundir/01.raw_align/03.raw_align.sh.work/raw_align01/nextDenovo.sh.e
hostname
+ hostname
cd /home/ubuntu/data/result/01_rundir/01.raw_align/03.raw_align.sh.work/raw_align01
+ cd /home/ubuntu/data/result/01_rundir/01.raw_align/03.raw_align.sh.work/raw_align01
time /home/ubuntu/software/NextDenovo/bin/minimap2-nd --step 1 --dual=yes -t 8 -x ava-ont /home/ubuntu/data/result/01_rundir/01.raw_align/input.seed.003.2bit /home/ubuntu/data/result/01_rundir/01.raw_align/
input.part.013.2bit -o input.seed.003.2bit.0.ovl;
+ time /home/ubuntu/software/NextDenovo/bin/minimap2-nd --step 1 --dual=yes -t 8 -x ava-ont /home/ubuntu/data/result/01_rundir/01.raw_align/input.seed.003.2bit /home/ubuntu/data/result/01_rundir/01.raw_alig
n/input.part.013.2bit -o input.seed.003.2bit.0.ovl
[M::mm_idx_gen::1.424*1.00] collected minimizers
[M::mm_idx_gen::1.606*1.06] sorted minimizers
[M::main::1.606*1.06] loaded/built the index for 3136 target sequence(s)
[M::mm_mapopt_update::1.630*1.06] mid_occ = 170
[M::mm_idx_stat] kmer size: 15; skip: 5; is_hpc: 0; #seq: 3136
[M::mm_idx_stat::1.646*1.06] distinct minimizers: 1028225 (86.31% are singletons); average occurrences: 1.915; average spacing: 2.962
Command terminated by signal 9
7.65user 0.76system 0:07.63elapsed 110%CPU (0avgtext+0avgdata 1281924maxresident)k
11584inputs+0outputs (19major+331545minor)pagefaults 0swaps

**Genome characteristics**
PCR product   700bp

**Config file**
Please paste the complete content of the Config file (`run.cfg`) to here.
[General]
job_type = local # local, slurm, sge, pbs, lsf
job_prefix = nextDenovo
task = all # all, correct, assemble
rewrite = yes # yes/no
deltmp = yes
parallel_jobs = 20 # number of tasks used to run in parallel
input_type = raw # raw, corrected
read_type = ont # clr, ont, hifi
input_fofn = input.fofn
workdir = 01_rundir

[correct_option]
read_cutoff = 400bp
genome_size = 0.7M # estimated genome size
sort_options = -m 40g -t 10
minimap2_options_raw = -t 8
pa_correction = 3 # number of corrected tasks used to run in parallel, each corrected task requires ~TOTAL_INPUT_BASES/4 bytes of memory usage.
correction_options = -p 15

[assemble_option]
minimap2_options_cns = -t 8
nextgraph_options = -a 1

# see https://nextdenovo.readthedocs.io/en/latest/OPTION.html for a detailed introduction about all the parameters

**Operating system**
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.4 LTS
Release:        18.04
Codename:       bionic

**GCC**
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/7/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 7.5.0-3ubuntu1~18.04' --with-bugurl=file:///usr/share/doc/gcc-7/README.Bugs --enable-languages=c,ada,c++,go,brig,d,fortran,objc,obj-c++ --prefix=/usr --with-gcc-major-version-only --program-suffix=-7 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-bootstrap --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --enable-default-pie --with-system-zlib --with-target-system-zlib --enable-objc-gc=auto --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 7.5.0 (Ubuntu 7.5.0-3ubuntu1~18.04)

**Python**
Python 3.8.5

**Comment by moold** [comment]
you don't have enough memory, try `parallel_jobs = 1` and `pa_correction=1`

**Comment by moold** [comment]
I just realized your genome is only 700k, I'm not sure if nextdenovo is suitable for this.

**Comment by kreyszhang** [comment]
> 
I'm so grateful, this worked.
This is a PCR product, so it is very short. And I'm not very good at this work , I don't know if there is any other assembly software suitable for short genome assembly with third-generation sequencing. I know that short genomes are not suitable for third-generation sequencing, but the time of TGS is shorter than NGS, so I still want to try it .
