### ISSUE TITLE
组装基因组大小

### ISSUE THREAD

**Issue by yilunhuangyue** [Nextomics/NextDenovo#14]
你好，在软件释放后立即初步体验了一下。使用的基因组预测大小为320M，杂合度为0.7%。最终N50达到了11M，基本达到了染色体水平，对这个水平非常惊喜。很感谢能开发出这样的软件。
但有一个问题，目前组装的基因组大小为273M，使用数据为nanopore raw data，参数均为默认。与其他软件相比（wtdbg2:293M，minimap+minisam：321M，SMARTdenovo：297M），还有一定差距，请问调节什么参数可以适当增大组装的基因组大小呢？
期待开发者的解答。后续也会继续使用反馈。再次感谢开发者做出的贡献~

**Comment by moold** [comment]
Try this option: random_round = 100 and you will get a total of 100 results with 100 random parameter sets. But please check the accuracy  of the assembly result using random parameters, which usually have more errors than the default result.
BTW, Could you use ENGLISH to ask help, which can provide some help to researchers in other countries.

**Comment by fengyuanli304** [comment]
Hi, Dr. Hu，I assemble the genome using NextDenovo2.3.1 and get a smaller genome size. We estimated the genome to be 544 Mb using flow cytometry. Could I adjust seed_cutoff using bin/seq_stat (from 30 to 44)? 
seq_stat -g 520Mb -d 45 

Type           Length (bp)            Count (#)
N10             18109579                   2
N20             15369455                   4
N30             14374265                   6
N40             13453187                   9
N50             10557259                  12
N60              8958888                  15
N70              7464108                  19
N80              5225030                  25
N90              1759737                  36

Min.               38332                   -
Max.            24878981                   -
Ave.             3230002                   -
Total          345610306                 107
Thank you for your reading and I am looking forward to your reply.

**Comment by moold** [comment]
yes, and also see [here](https://nextdenovo.readthedocs.io/en/latest/FAQ.html#how-to-adjust-parameters-if-the-assembly-size-is-smaller-than-the-expected-genome-size)
