### ISSUE TITLE
What are the parts of contig titles mean for?

### ISSUE THREAD

**Issue by xbx-xbx-1208** [Nextomics/NextDenovo#144]
**Question or Expected behavior**
A clear and concise description of your question or what you expected to happen.
Just like the title.
**Operating system**
Which operating system and version are you using?
You can use the command `lsb_release -a` to get it.
Centos-7
**GCC**
What version of GCC are you using?
You can use the command `gcc -v` to get it.

**Python**
What version of Python are you using?
You can use the command `python --version` to get it.

**NextDenovo**
What version of NextDenovo are you using?
You can use the command `nextDenovo -v` to get it.
2.4.0
**Additional context** (Optional)
>ctg000110 type:s:linear length:i:102686 node:i:8
>ctg000120 type:s:linear length:i:489762 node:i:67
>ctg000130 type:s:linear length:i:55111 node:s:unknown
>ctg000140 type:s:linear length:i:390488 node:s:unknown
I found the titles of my contigs like above, and want know their meanings. Like "type:s:linear", and what the difference between "node:s:unknown" and "node:i:8" ?

**Comment by moold** [comment]
The `8` in `node:i:8` means there are 8 complete reads in this contig,
The `unknown` in  "node:s:unknown" means some reads are split, so it can not give an exact read number.

**Comment by xbx-xbx-1208** [comment]
谢谢您的回复，还想请教一下，那些unknown的contig是否需要剔除，就像使用canu时，可以根据contig的信息手动剔除一些contig；或者说，关于nextdenovo这些contig的开头信息的说明在哪里找到详细的说明呢？



---- 回复的原邮件 ----
| 发件人 | Hu ***@***.***> |
| 日期 | 2022年03月31日 12:54 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [Nextomics/NextDenovo] What are the parts of contig titles mean for? (Issue #144) |

The 8 in node:i:8 means there are 8 complete reads in this contig,
The unknown in "node:s:unknown" means some reads are split, so it can not give an exact read number.

**Comment by moold** [comment]
No
