### ISSUE TITLE
How to know which reads are used in the assembled conting

### ISSUE THREAD

**Issue by kuangzhuoran** [Nextomics/NextDenovo#149]
**Question or Expected behavior**
How to know which reads are used in the assembled conting

**Operating system**
Linux

**GCC**
gcc version 8.5.0 20210514 (Red Hat 8.5.0-4) (GCC)

**Python**
Python 3.8.3

**NextDenovo**
nextDenovo v2.5.0

**Comment by moold** [comment]
The easiest way is to map the corrected reads to the assembly sequences.
