### ISSUE TITLE
#returned non-zero exit status 137, error info: .#

### ISSUE THREAD

**Issue by lide1993** [Nextomics/NextDenovo#151]
Hi, Dr. Hu
I ran into this problem when I assembled the genome from ONT data and couldn't solve it:
**Describe the bug**
#returned non-zero exit status 137, error info: .#
hostname
+ hostname
cd /home/victor/NextDenovo/01_rundir/01.raw_align/03.raw_align.sh.work/raw_align03
+ cd /home/victor/NextDenovo/01_rundir/01.raw_align/03.raw_align.sh.work/raw_align03
time /home/victor/NextDenovo/bin/minimap2-nd --step 1 --dual=yes -x ava-ont -t 4 /home/victor/NextDenovo/01_rundir/01.raw_align/input.seed.002.2bit /home/victor/NextDenovo/01_rundir/01.raw_align/input.part.004.2bit -o input.seed.002.2bit.2.ovl;
+ time /home/victor/NextDenovo/bin/minimap2-nd --step 1 --dual=yes -x ava-ont -t 4 /home/victor/NextDenovo/01_rundir/01.raw_align/input.seed.002.2bit /home/victor/NextDenovo/01_rundir/01.raw_align/input.part.004.2bit -o input.seed.002.2bit.2.ovl
Command terminated by signal 9
136.84user 42.79system 10:54.44elapsed 27%CPU (0avgtext+0avgdata 16223296maxresident)k
779264inputs+0outputs (19435major+12120401minor)pagefaults 0swaps

**Genome characteristics**
`genome size 336Mb,
 [General]
job_type = local
job_prefix = nextDenovopomegranate0816
task = all # 'all', 'correct', 'assemble'
rewrite = yes # yes/no
deltmp = yes
rerun = 3
parallel_jobs = 8
input_type = raw
read_type = ont
input_fofn = input.fofn
workdir = 01_rundir

[correct_option]
read_cutoff = 1k
genome_size = 336M
pa_correction = 3
sort_options = -m 3g -t 10
minimap2_options_raw = -x ava-ont -t 4
correction_options = -p 15

[assemble_option]
minimap2_options_cns = -x ava-ont -t 4 -k 21 -w 21
nextgraph_options = -a 1

**Comment by moold** [comment]
How much RAM does your computer have?

**Comment by lide1993** [comment]
> 
hi，Dr. Hu

MemTotal:       98753020 kB
MemFree:        85963008 kB
MemAvailable:   96948512 kB
Buffers:          767056 kB
Cached:         10186696 kB
SwapCached:        17036 kB
Active:          1346316 kB
Inactive:        9709300 kB
Active(anon):      50588 kB
Inactive(anon):    44028 kB
Active(file):    1295728 kB
Inactive(file):  9665272 kB
Unevictable:           0 kB
Mlocked:               0 kB
SwapTotal:       2097148 kB
SwapFree:        1806548 kB
Dirty:                 0 kB
Writeback:             0 kB
AnonPages:         86196 kB
Mapped:            82792 kB
Shmem:              1200 kB
KReclaimable:     890620 kB
Slab:            1382476 kB
SReclaimable:     890620 kB
SUnreclaim:       491856 kB
KernelStack:       13200 kB
PageTables:        11728 kB
NFS_Unstable:          0 kB
Bounce:                0 kB
WritebackTmp:          0 kB
CommitLimit:    51473656 kB
Committed_AS:    3832172 kB
VmallocTotal:   34359738367 kB
VmallocUsed:      151228 kB
VmallocChunk:          0 kB
Percpu:            55808 kB
HardwareCorrupted:     0 kB
AnonHugePages:         0 kB
ShmemHugePages:        0 kB
ShmemPmdMapped:        0 kB
FileHugePages:         0 kB
FilePmdMapped:         0 kB
CmaTotal:              0 kB
CmaFree:               0 kB
HugePages_Total:       0
HugePages_Free:        0
HugePages_Rsvd:        0
HugePages_Surp:        0
Hugepagesize:       2048 kB
Hugetlb:               0 kB
DirectMap4k:     2192244 kB
DirectMap2M:    97189888 kB
DirectMap1G:     3145728 kB

**Comment by lide1993** [comment]
> How much RAM does your computer have?
hi，Dr. Hu
MemTotal: 98753020 kB
MemFree: 85963008 kB
MemAvailable: 96948512 kB
Buffers: 767056 kB
Cached: 10186696 kB
SwapCached: 17036 kB
Active: 1346316 kB
Inactive: 9709300 kB
Active(anon): 50588 kB
Inactive(anon): 44028 kB
Active(file): 1295728 kB
Inactive(file): 9665272 kB
Unevictable: 0 kB
Mlocked: 0 kB
SwapTotal: 2097148 kB
SwapFree: 1806548 kB
Dirty: 0 kB
Writeback: 0 kB
AnonPages: 86196 kB
Mapped: 82792 kB
Shmem: 1200 kB
KReclaimable: 890620 kB
Slab: 1382476 kB
SReclaimable: 890620 kB
SUnreclaim: 491856 kB
KernelStack: 13200 kB
PageTables: 11728 kB
NFS_Unstable: 0 kB
Bounce: 0 kB
WritebackTmp: 0 kB
CommitLimit: 51473656 kB
Committed_AS: 3832172 kB
VmallocTotal: 34359738367 kB
VmallocUsed: 151228 kB
VmallocChunk: 0 kB
Percpu: 55808 kB
HardwareCorrupted: 0 kB
AnonHugePages: 0 kB
ShmemHugePages: 0 kB
ShmemPmdMapped: 0 kB
FileHugePages: 0 kB
FilePmdMapped: 0 kB
CmaTotal: 0 kB
CmaFree: 0 kB
HugePages_Total: 0
HugePages_Free: 0
HugePages_Rsvd: 0
HugePages_Surp: 0
Hugepagesize: 2048 kB
Hugetlb: 0 kB
DirectMap4k: 2192244 kB
DirectMap2M: 97189888 kB
DirectMap1G: 3145728 kB

**Comment by moold** [comment]
Try the following config
```
parallel_jobs =1
pa_correction = 1
sort_options = -m 3g -t 30
minimap2_options_raw = -x ava-ont -t 32
correction_options = -p 30
minimap2_options_cns = -x ava-ont -t 32 -k 21 -w 21
```
