### ISSUE TITLE
Error in cns_align1 step

### ISSUE THREAD

**Issue by Tata12306** [Nextomics/NextDenovo#165]
Hi moold！

**Question or Expected behavior**
This is my first time to use nextdenove.
This is my working path：01_rundir/02.cns_align/02.cns_align.sh.work/cns_align1
I have six such tasks, which have been running for a long time, and the result log is no longer updated. I want to ask what the problem is. Or what else do I need to provide?

**NextDenovo**
nextDenovo v2.5.0
I use slurm delivery system.

This is my log
[nextDenovo.sh.e.txt](https://github.com/Nextomics/NextDenovo/files/10681304/nextDenovo.sh.e.txt)

**Comment by moold** [comment]
Could you try to use the command `top` to check wether the cpu TIME is increasing.
If it is , just wait, or kill it and rerun .

**Comment by Tata12306** [comment]
OK，Thanks！
