### ISSUE TITLE
Only one sample or multiple samples can be used in nextdenovo?

### ISSUE THREAD

**Issue by xbx-xbx-1208** [Nextomics/NextDenovo#166]
**Question or Expected behavior**
Hi, following are my two question about the use of nextdenovo.
I wonder whether the multiple ccs sequencing files can be derived from several samples, or are supposed to be derived from only one individual?
As the animal we would like to get genome is tiny in size, only one animal probably can't produce enough sequencing data. We hope to know if we can use several animals for sequencing and utilize the data from multile sources for assembly?
By the way, this kind of animal is wild rather than domestic. The results of genome survey demonstrate the heterozygosity is high (~0.5%); whether this can cause further influence to genome assembly?

**Operating system**
LSB Version: :core-4.1-amd64:core-4.1-noarch
Distributor ID: CentOS
Description: CentOS Linux release 7.9.2009 (Core)
Release: 7.9.2009
Codename: Core

**GCC**
gcc version 4.8.5 20150623 (Red Hat 4.8.5-44) (GCC)

**Python**
Python 3.9.12

**NextDenovo**
nextDenovo v2.5.0.

**Additional context** (Optional)

**Comment by moold** [comment]
Hi，Nextdenovo is not optimized for hifi data, so it is not suitable for hifi data by now, so try other assemblers first.
