### ISSUE TITLE
[ERROR] failed to find seq file type or empty file after ctg_graph

### ISSUE THREAD

**Issue by etd530** [Nextomics/NextDenovo#168]
Dear Devs,

I am trying to assemble the genome of a bacterial endosymbiont from PacBio CLR reads generated for its host. We have a previous assembly made with another assembler, but we want to improve it. The expected genome size is ~1.5Mb.

When NextDenovo reaches the ctg_graph job it finishes with the error `[ERROR] failed to find seq file type or empty file`; the file `nd.asm.p.fasta` is empty.

Here is the main task log: [pid12305.log.txt](https://github.com/Nextomics/NextDenovo/files/10902271/pid12305.log.txt)

The config file is as follows (I also tried with defaults for seed_cutoff and for -k in sort_options):
```
[General]
job_type = local
job_prefix = erebia_ligea.RO_EL_949.nonBfly.nextdenovo
task = all # 'all', 'correct', 'assemble'
rewrite = yes # yes/no
deltmp = yes
rerun = 0
parallel_jobs = 5
input_type = raw
read_type = clr
input_fofn = /scratch/etoro/erebia/nextdenovo/erebia_ligea.RO_EL_949.nonBfly.nextdenovo.fofn
workdir = /scratch/etoro/erebia/nextdenovo

[correct_option]
read_cutoff = 1k
genome_size = 1500000
pa_correction = 5
sort_options = -m 40g -t 20 -k 80
minimap2_options_raw =  -t 12
correction_options = -p 13
seed_cutoff = 10000

[assemble_option]
minimap2_options_cns =  -t 12
nextgraph_options = -a 1
```

OS version: Ubuntu 18.04.1 LTS
GCC version: 6.3.0 20170516 (Debian 6.3.0-18+deb9u1)
Python version: 3.7.13
NextDenovo: 2.4.0

Many thanks,

Eric

**Comment by moold** [comment]
Could you paste the content of file  `/scratch/etoro/erebia/nextdenovo/03.ctg_graph/01.ctg_graph.sh.work/ctg_graph0/erebia_ligea.RO_EL_949.nonBfly.nextdenovo.sh.e` to here?

**Comment by moold** [comment]
Try to reduce `-z -l` first and if the result is still empty then reduce  these options:  `-q -N -u -w -B -C -z -l -L -t `.

**Comment by czhsysu** [comment]
I also meet the same problem, but  my  read type is ont and I don't know how to fix it

**Comment by PuziJiang** [comment]
I meet the same problem when I am assembling nanopore sequencing data of microbes. The nextgraph option I used were -a 1 -z 4 -l 8 -q 0 -N 2 -u 2 -w 2 -B 200 -C 15 -L 3 -t 300, it still didn't work.
