### ISSUE TITLE
Parallel job parameter of NextDenovo when run in local mode

### ISSUE THREAD

**Issue by xuzhougeng** [Nextomics/NextDenovo#17]
Hi,

Could you tell me what is the relationship among the following parallel parameters

- paralle_job 
- pa_correction
- minimap2_options_raw 
- sort_options 
- correction_options 
- minimap2_options_cns 

In the default parameters(parallel_jobs = 10, pa_correction = 15, minimap2_options_raw = -x ava-ont -t 10  ), would the nextDenovo  use 10 * 15 *10 = 1500 CPU or 15 * 10 = 150 in correction stage.

**Comment by moold** [comment]
+ `paralle_job` is used to control how many tasks (except correction task) will run at the same time. 
+ `pa_correction` is used to control how many correction  tasks will run at the same time. 
+ All other options are used to control how many threads will use for only one job.
