### ISSUE TITLE
about the  ParallelTask for the nextdenovo

### ISSUE THREAD

**Issue by fly005304** [Nextomics/NextDenovo#171]
Dear Author,
     I think that this new version for use the ParallelTask is not very well for different groups.  As in some institutes, different user has different queue and project ID for subbmit their job to the SGE, but they can't change this for diffferent people. So i suggest the author to revise this just as the before version that we can change it in the cfg file.
Best,
Xuanmin

**Comment by moold** [comment]
Two choices:
1. You can set the [submit](https://nextdenovo.readthedocs.io/en/latest/OPTION.html#cmdoption-arg-submit) optipon like this: `submit = qsub -pe smp {cpu} -l vf={mem} -o {out} -e {err} {script}` in the NextDenovo configure file.
2. Install a standalone python for yourself only.
