### ISSUE TITLE
Low performance with highly repeated regions

### ISSUE THREAD

**Issue by leone93** [Nextomics/NextDenovo#173]
I'm using the last version of the software 2.5.2 to assembly some HiFi reads of different plant species (with coverage over 60x).
I notice that if the content of transposable elements (or generally repeated regions) increased, the contiguity of the asseambly drop substancially. Do you have any idea of the parameter that maybe is possible to tweak to solve this things?
Thanks

**Comment by moold** [comment]
As I said in other issues, NextDenovo is not optimized for hifi data, so try other assemblers first.
