### ISSUE TITLE
Unable to run test data on macOS

### ISSUE THREAD

**Issue by ianaebutler** [Nextomics/NextDenovo#175]
**Describe the bug**
I downloaded NextDenovo and I am unable to run it using the test data. I haven't made any changes to the config file or the input data. Any help would be appreciated.

**Error message**

Here is the main task log
<pre>
[64468 INFO] 2023-05-30 14:53:29 NextDenovo start...
[64468 INFO] 2023-05-30 14:53:29 version:2.5.2 logfile:pid64468.log.info
[64468 WARNING] 2023-05-30 14:53:29 Re-write workdir
[64468 INFO] 2023-05-30 14:53:29 skip mkdir: /Users/ianbutler/Documents/NextDenovo/test_data/./01_rundir
[64468 INFO] 2023-05-30 14:53:29 skip mkdir: /Users/ianbutler/Documents/NextDenovo/test_data/./01_rundir/01.raw_align
[64468 INFO] 2023-05-30 14:53:29 skip mkdir: /Users/ianbutler/Documents/NextDenovo/test_data/./01_rundir/02.cns_align
[64468 INFO] 2023-05-30 14:53:29 skip mkdir: /Users/ianbutler/Documents/NextDenovo/test_data/./01_rundir/03.ctg_graph
[64468 INFO] 2023-05-30 14:53:34 Total jobs: 1
[64468 INFO] 2023-05-30 14:53:34 Submitted jobID:[64473] jobCmd:[/Users/ianbutler/Documents/NextDenovo/test_data/01_rundir/01.raw_align/01.db_stat.sh.work/db_stat1/nextDenovo.sh] in the local_cycle.
[64473 CRITICAL] 2023-05-30 14:53:34 Command '/bin/bash /Users/ianbutler/Documents/NextDenovo/test_data/01_rundir/01.raw_align/01.db_stat.sh.work/db_stat1/nextDenovo.sh > /Users/ianbutler/Documents/NextDenovo/test_data/01_rundir/01.raw_align/01.db_stat.sh.work/db_stat1/nextDenovo.sh.o 2> /Users/ianbutler/Documents/NextDenovo/test_data/01_rundir/01.raw_align/01.db_stat.sh.work/db_stat1/nextDenovo.sh.e' returned non-zero exit status 126, error info: .
[64468 ERROR] 2023-05-30 14:53:40 db_stat failed: please check the following logs:
[64468 ERROR] 2023-05-30 14:53:40 /Users/ianbutler/Documents/NextDenovo/test_data/01_rundir/01.raw_align/01.db_stat.sh.work/db_stat1/nextDenovo.sh.e
</pre>

and the subtask log

<pre>
hostname
+ hostname
cd /Users/ianbutler/Documents/NextDenovo/test_data/01_rundir/01.raw_align/01.db_stat.sh.work/db_stat1
+ cd /Users/ianbutler/Documents/NextDenovo/test_data/01_rundir/01.raw_align/01.db_stat.sh.work/db_stat1
( time  /Users/ianbutler/Documents/NextDenovo/bin/seq_stat -f 1k -g 308161 -d 45 -o /Users/ianbutler/Documents/NextDenovo/test_data/01_rundir/01.raw_align/input.reads.stat /Users/ianbutler/Documents/NextDenovo/test_data/input.fofn )
+ /Users/ianbutler/Documents/NextDenovo/bin/seq_stat -f 1k -g 308161 -d 45 -o /Users/ianbutler/Documents/NextDenovo/test_data/01_rundir/01.raw_align/input.reads.stat /Users/ianbutler/Documents/NextDenovo/test_data/input.fofn
/Users/ianbutler/Documents/NextDenovo/test_data/01_rundir/01.raw_align/01.db_stat.sh.work/db_stat1/nextDenovo.sh: line 5: /Users/ianbutler/Documents/NextDenovo/bin/seq_stat: cannot execute binary file
</pre>

**Operating system**
macOS Monterey v12.5.1

**GCC**
Apple clang version 14.0.0 (clang-1400.0.29.202)
Target: arm64-apple-darwin21.6.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin

**Python**
Python 3.10.10

**NextDenovo**
nextDenovo 2.5.2

**Comment by moold** [comment]
Did you install `NextDenovo` from the source?

**Comment by ianaebutler** [comment]
In my first comment, I downloaded the NextDenovo.tgz file from the link in readthedocs. I just tried to install it from the source and I got a lot of error messages when I tried to compile.

<pre>
make -C minimap2;  make -C util;  make -C lib;
cc -c -g -Wall -O2 -Wc++-compat -Wno-unused-function  -DHAVE_KALLOC  main.c -o main.o
cc -c -g -Wall -O2 -Wc++-compat -Wno-unused-function  -DHAVE_KALLOC  kthread.c -o kthread.o
cc -c -g -Wall -O2 -Wc++-compat -Wno-unused-function  -DHAVE_KALLOC  kalloc.c -o kalloc.o
cc -c -g -Wall -O2 -Wc++-compat -Wno-unused-function  -DHAVE_KALLOC  misc.c -o misc.o
cc -c -g -Wall -O2 -Wc++-compat -Wno-unused-function  -DHAVE_KALLOC  bseq.c -o bseq.o
cc -c -g -Wall -O2 -Wc++-compat -Wno-unused-function  -DHAVE_KALLOC  sketch.c -o sketch.o
cc -c -g -Wall -O2 -Wc++-compat -Wno-unused-function  -DHAVE_KALLOC  sdust.c -o sdust.o
cc -c -g -Wall -O2 -Wc++-compat -Wno-unused-function  -DHAVE_KALLOC  options.c -o options.o
cc -c -g -Wall -O2 -Wc++-compat -Wno-unused-function  -DHAVE_KALLOC  index.c -o index.o
cc -c -g -Wall -O2 -Wc++-compat -Wno-unused-function  -DHAVE_KALLOC  chain.c -o chain.o
cc -c -g -Wall -O2 -Wc++-compat -Wno-unused-function  -DHAVE_KALLOC  align.c -o align.o
cc -c -g -Wall -O2 -Wc++-compat -Wno-unused-function  -DHAVE_KALLOC  hit.c -o hit.o
cc -c -g -Wall -O2 -Wc++-compat -Wno-unused-function  -DHAVE_KALLOC  map.c -o map.o
cc -c -g -Wall -O2 -Wc++-compat -Wno-unused-function  -DHAVE_KALLOC  format.c -o format.o
cc -c -g -Wall -O2 -Wc++-compat -Wno-unused-function  -DHAVE_KALLOC  pe.c -o pe.o
cc -c -g -Wall -O2 -Wc++-compat -Wno-unused-function  -DHAVE_KALLOC  esterr.c -o esterr.o
cc -c -g -Wall -O2 -Wc++-compat -Wno-unused-function  -DHAVE_KALLOC  splitidx.c -o splitidx.o
cc -c -g -Wall -O2 -Wc++-compat -Wno-unused-function  -msse2 -DHAVE_KALLOC  ksw2_ll_sse.c -o ksw2_ll_sse.o
clang: warning: argument unused during compilation: '-msse2' [-Wunused-command-line-argument]
In file included from ksw2_ll_sse.c:4:
/Library/Developer/CommandLineTools/usr/lib/clang/14.0.0/include/emmintrin.h:14:2: error: "This header is only meant to be used on x86 and x64 architecture"
#error "This header is only meant to be used on x86 and x64 architecture"
 ^
In file included from ksw2_ll_sse.c:4:
In file included from /Library/Developer/CommandLineTools/usr/lib/clang/14.0.0/include/emmintrin.h:17:
/Library/Developer/CommandLineTools/usr/lib/clang/14.0.0/include/xmmintrin.h:14:2: error: "This header is only meant to be used on x86 and x64 architecture"
#error "This header is only meant to be used on x86 and x64 architecture"
 ^
In file included from ksw2_ll_sse.c:4:
In file included from /Library/Developer/CommandLineTools/usr/lib/clang/14.0.0/include/emmintrin.h:17:
In file included from /Library/Developer/CommandLineTools/usr/lib/clang/14.0.0/include/xmmintrin.h:17:
/Library/Developer/CommandLineTools/usr/lib/clang/14.0.0/include/mmintrin.h:14:2: error: "This header is only meant to be used on x86 and x64 architecture"
#error "This header is only meant to be used on x86 and x64 architecture"
 ^
/Library/Developer/CommandLineTools/usr/lib/clang/14.0.0/include/mmintrin.h:54:12: error: invalid conversion between vector type '__m64' (vector of 1 'long long' value) and integer type 'int' of different size
    return (__m64)__builtin_ia32_vec_init_v2si(__i, 0);
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Library/Developer/CommandLineTools/usr/lib/clang/14.0.0/include/mmintrin.h:133:12: error: invalid conversion between vector type '__m64' (vector of 1 'long long' value) and integer type 'int' of different size
    return (__m64)__builtin_ia32_packsswb((__v4hi)__m1, (__v4hi)__m2);
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Library/Developer/CommandLineTools/usr/lib/clang/14.0.0/include/mmintrin.h:163:12: error: invalid conversion between vector type '__m64' (vector of 1 'long long' value) and integer type 'int' of different size
    return (__m64)__builtin_ia32_packssdw((__v2si)__m1, (__v2si)__m2);
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Library/Developer/CommandLineTools/usr/lib/clang/14.0.0/include/mmintrin.h:193:12: error: invalid conversion between vector type '__m64' (vector of 1 'long long' value) and integer type 'int' of different size
    return (__m64)__builtin_ia32_packuswb((__v4hi)__m1, (__v4hi)__m2);
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Library/Developer/CommandLineTools/usr/lib/clang/14.0.0/include/mmintrin.h:220:12: error: invalid conversion between vector type '__m64' (vector of 1 'long long' value) and integer type 'int' of different size
    return (__m64)__builtin_ia32_punpckhbw((__v8qi)__m1, (__v8qi)__m2);
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Library/Developer/CommandLineTools/usr/lib/clang/14.0.0/include/mmintrin.h:243:12: error: invalid conversion between vector type '__m64' (vector of 1 'long long' value) and integer type 'int' of different size
    return (__m64)__builtin_ia32_punpckhwd((__v4hi)__m1, (__v4hi)__m2);
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Library/Developer/CommandLineTools/usr/lib/clang/14.0.0/include/mmintrin.h:264:12: error: invalid conversion between vector type '__m64' (vector of 1 'long long' value) and integer type 'int' of different size
    return (__m64)__builtin_ia32_punpckhdq((__v2si)__m1, (__v2si)__m2);
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Library/Developer/CommandLineTools/usr/lib/clang/14.0.0/include/mmintrin.h:291:12: error: invalid conversion between vector type '__m64' (vector of 1 'long long' value) and integer type 'int' of different size
    return (__m64)__builtin_ia32_punpcklbw((__v8qi)__m1, (__v8qi)__m2);
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Library/Developer/CommandLineTools/usr/lib/clang/14.0.0/include/mmintrin.h:314:12: error: invalid conversion between vector type '__m64' (vector of 1 'long long' value) and integer type 'int' of different size
    return (__m64)__builtin_ia32_punpcklwd((__v4hi)__m1, (__v4hi)__m2);
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Library/Developer/CommandLineTools/usr/lib/clang/14.0.0/include/mmintrin.h:335:12: error: invalid conversion between vector type '__m64' (vector of 1 'long long' value) and integer type 'int' of different size
    return (__m64)__builtin_ia32_punpckldq((__v2si)__m1, (__v2si)__m2);
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Library/Developer/CommandLineTools/usr/lib/clang/14.0.0/include/mmintrin.h:356:12: error: invalid conversion between vector type '__m64' (vector of 1 'long long' value) and integer type 'int' of different size
    return (__m64)__builtin_ia32_paddb((__v8qi)__m1, (__v8qi)__m2);
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Library/Developer/CommandLineTools/usr/lib/clang/14.0.0/include/mmintrin.h:377:12: error: invalid conversion between vector type '__m64' (vector of 1 'long long' value) and integer type 'int' of different size
    return (__m64)__builtin_ia32_paddw((__v4hi)__m1, (__v4hi)__m2);
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Library/Developer/CommandLineTools/usr/lib/clang/14.0.0/include/mmintrin.h:398:12: error: invalid conversion between vector type '__m64' (vector of 1 'long long' value) and integer type 'int' of different size
    return (__m64)__builtin_ia32_paddd((__v2si)__m1, (__v2si)__m2);
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Library/Developer/CommandLineTools/usr/lib/clang/14.0.0/include/mmintrin.h:420:12: error: invalid conversion between vector type '__m64' (vector of 1 'long long' value) and integer type 'int' of different size
    return (__m64)__builtin_ia32_paddsb((__v8qi)__m1, (__v8qi)__m2);
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Library/Developer/CommandLineTools/usr/lib/clang/14.0.0/include/mmintrin.h:443:12: error: invalid conversion between vector type '__m64' (vector of 1 'long long' value) and integer type 'int' of different size
    return (__m64)__builtin_ia32_paddsw((__v4hi)__m1, (__v4hi)__m2);
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Library/Developer/CommandLineTools/usr/lib/clang/14.0.0/include/mmintrin.h:465:12: error: invalid conversion between vector type '__m64' (vector of 1 'long long' value) and integer type 'int' of different size
    return (__m64)__builtin_ia32_paddusb((__v8qi)__m1, (__v8qi)__m2);
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make[1]: *** [ksw2_ll_sse.o] Error 1
gcc -Wall -O3 -Wno-unused-function   -o seq_dump seq_dump.c ../lib/bseq.c -lz
seq_dump.c:39:40: warning: format specifies type 'unsigned long' but the argument has type 'unsigned long long' [-Wformat]
  fprintf(idx, "%u\t%lu\t%u\n", n_cnt, *start + 8, n);
                    ~~~                ^~~~~~~~~~
                    %llu
1 warning generated.
gcc -Wall -O3 -Wno-unused-function  -std=c99 -pthread  -o ovl_sort ovl_sort.c thpool.c ../lib/ovl.c
ovl_sort.c:123:38: warning: format specifies type 'unsigned long *' but the argument has type 'uint64_t *' (aka 'unsigned long long *') [-Wformat]
                sscanf(line, "%u\t%lu\t%u", &name, &offset, &length);
                                  ~~~              ^~~~~~~
                                  %llu
ovl_sort.c:680:40: warning: taking the absolute value of unsigned type 'unsigned int' has no effect [-Wabsolute-value]
                if ((j > 15 || k < cov->len - 16) && abs(ovl->qs - cov->qs) < BIN_TOLERANCE_EDGE && \
                                                     ^
ovl_sort.c:680:40: note: remove the call to 'abs' since unsigned values cannot be negative
                if ((j > 15 || k < cov->len - 16) && abs(ovl->qs - cov->qs) < BIN_TOLERANCE_EDGE && \
                                                     ^~~
ovl_sort.c:681:5: warning: taking the absolute value of unsigned type 'unsigned int' has no effect [-Wabsolute-value]
                                abs(ovl->qe - cov->qe) < BIN_TOLERANCE_EDGE){
                                ^
ovl_sort.c:681:5: note: remove the call to 'abs' since unsigned values cannot be negative
                                abs(ovl->qe - cov->qe) < BIN_TOLERANCE_EDGE){
                                ^~~
3 warnings generated.
thpool.c:329:2: error: implicit declaration of function 'pthread_setname_np' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
        pthread_setname_np(thread_name);
        ^
1 error generated.
make[1]: *** [ovl_sort] Error 1
gcc -std=c99 -O3 -Wall -Wno-unused-function -fPIC -shared  -o nextcorrect.so align.c dag.c nextcorrect.c 
gcc -std=c99 -O3 -Wall -Wno-unused-function -fPIC -shared  -o ovlseq.so ovlseq.c bseq.c ovl.c index.c -lz
index.c:24:38: warning: format specifies type 'unsigned long *' but the argument has type 'uint64_t *' (aka 'unsigned long long *') [-Wformat]
                sscanf(line, "%u\t%lu\t%u", &name, &offset, &length);//%hu\t
                                  ~~~              ^~~~~~~
                                  %llu
index.c:56:38: warning: format specifies type 'unsigned long *' but the argument has type 'uint64_t *' (aka 'unsigned long long *') [-Wformat]
                sscanf(line, "%u\t%lu\t%u", &name, &offset, &length);//%hu\t
                                  ~~~              ^~~~~~~
                                  %llu
2 warnings generated.
cd  ./htslib/ && ./configure  --disable-bz2 --disable-lzma
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking for ranlib... ranlib
checking for grep that handles long lines and -e... /usr/bin/grep
checking for C compiler warning flags... -Wall
checking for special C compiler options needed for large files... no
checking for _FILE_OFFSET_BITS value needed for large files... no
checking for _LARGEFILE_SOURCE value needed for large files... no
checking shared library type for unknown-Darwin... Darwin dylib
checking how to run the C preprocessor... gcc -E
checking for egrep... /usr/bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for stdlib.h... (cached) yes
checking for unistd.h... (cached) yes
checking for sys/param.h... yes
checking for getpagesize... yes
checking for working mmap... yes
checking for gmtime_r... yes
checking for fsync... yes
checking for drand48... yes
checking whether fdatasync is declared... no
checking for library containing log... none required
checking for zlib.h... yes
checking for inflate in -lz... yes
checking for library containing recv... none required
checking for libdeflate.h... no
checking for libdeflate_deflate_compress in -ldeflate... no
checking for curl_easy_pause in -lcurl... yes
checking for CCHmac... yes
checking whether PTHREAD_MUTEX_RECURSIVE is declared... yes
configure: creating ./config.status
config.status: creating config.mk
config.status: creating htslib.pc.tmp
config.status: creating config.h
gcc -Wall -g -O2 -I. -fPIC -c -o kfunc.o kfunc.c
gcc -Wall -g -O2 -I. -fPIC -c -o knetfile.o knetfile.c
gcc -Wall -g -O2 -I. -fPIC -c -o kstring.o kstring.c
gcc -Wall -g -O2 -I. -fPIC -c -o bcf_sr_sort.o bcf_sr_sort.c
gcc -Wall -g -O2 -I. -fPIC -c -o bgzf.o bgzf.c
bgzf.c:1160:16: warning: variable 'size' set but not used [-Wunused-but-set-variable]
    int count, size = 0, block_length, remaining;
               ^
1 warning generated.
gcc -Wall -g -O2 -I. -fPIC -c -o errmod.o errmod.c
gcc -Wall -g -O2 -I. -fPIC -c -o faidx.o faidx.c
gcc -Wall -g -O2 -I. -fPIC -c -o hfile.o hfile.c
gcc -Wall -g -O2 -I. -fPIC -c -o hfile_net.o hfile_net.c
echo '#define HTS_VERSION "1.9"' > version.h
gcc -Wall -g -O2 -I. -fPIC -c -o hts.o hts.c
gcc -Wall -g -O2 -I. -fPIC -c -o hts_os.o hts_os.c
gcc -Wall -g -O2 -I. -fPIC -c -o md5.o md5.c
gcc -Wall -g -O2 -I. -fPIC -c -o multipart.o multipart.c
gcc -Wall -g -O2 -I. -fPIC -c -o probaln.o probaln.c
gcc -Wall -g -O2 -I. -fPIC -c -o realn.o realn.c
gcc -Wall -g -O2 -I. -fPIC -c -o regidx.o regidx.c
gcc -Wall -g -O2 -I. -fPIC -c -o sam.o sam.c
gcc -Wall -g -O2 -I. -fPIC -c -o synced_bcf_reader.o synced_bcf_reader.c
gcc -Wall -g -O2 -I. -fPIC -c -o vcf_sweep.o vcf_sweep.c
gcc -Wall -g -O2 -I. -fPIC -c -o tbx.o tbx.c
gcc -Wall -g -O2 -I. -fPIC -c -o textutils.o textutils.c
gcc -Wall -g -O2 -I. -fPIC -c -o thread_pool.o thread_pool.c
gcc -Wall -g -O2 -I. -fPIC -c -o vcf.o vcf.c
vcf.c:641:14: warning: variable 'needs_sync' set but not used [-Wunused-but-set-variable]
    int len, needs_sync = 0, done = 0;
             ^
vcf.c:2826:50: warning: variable 'ret' set but not used [-Wunused-but-set-variable]
    int i, ndst_ori = dst->nhrec, need_sync = 0, ret = 0;
                                                 ^
2 warnings generated.
gcc -Wall -g -O2 -I. -fPIC -c -o vcfutils.o vcfutils.c
gcc -Wall -g -O2 -I. -fPIC -c -o cram/cram_codecs.o cram/cram_codecs.c
cram/cram_codecs.c:1243:19: warning: variable 'ntot' set but not used [-Wunused-but-set-variable]
    int nvals, i, ntot = 0, max_val = 0, min_val = INT_MAX, k;
                  ^
1 warning generated.
gcc -Wall -g -O2 -I. -fPIC -c -o cram/cram_decode.o cram/cram_decode.c
gcc -Wall -g -O2 -I. -fPIC -c -o cram/cram_encode.o cram/cram_encode.c
gcc -Wall -g -O2 -I. -fPIC -c -o cram/cram_external.o cram/cram_external.c
gcc -Wall -g -O2 -I. -fPIC -c -o cram/cram_index.o cram/cram_index.c
gcc -Wall -g -O2 -I. -fPIC -c -o cram/cram_io.o cram/cram_io.c
gcc -Wall -g -O2 -I. -fPIC -c -o cram/cram_samtools.o cram/cram_samtools.c
gcc -Wall -g -O2 -I. -fPIC -c -o cram/cram_stats.o cram/cram_stats.c
gcc -Wall -g -O2 -I. -fPIC -c -o cram/files.o cram/files.c
gcc -Wall -g -O2 -I. -fPIC -c -o cram/mFILE.o cram/mFILE.c
gcc -Wall -g -O2 -I. -fPIC -c -o cram/open_trace_file.o cram/open_trace_file.c
gcc -Wall -g -O2 -I. -fPIC -c -o cram/pooled_alloc.o cram/pooled_alloc.c
gcc -Wall -g -O2 -I. -fPIC -c -o cram/rANS_static.o cram/rANS_static.c
gcc -Wall -g -O2 -I. -fPIC -c -o cram/sam_header.o cram/sam_header.c
gcc -Wall -g -O2 -I. -fPIC -c -o cram/string_alloc.o cram/string_alloc.c
gcc -Wall -g -O2 -I. -fPIC -c -o hfile_libcurl.o hfile_libcurl.c
gcc -Wall -g -O2 -I. -fPIC -c -o hfile_gcs.o hfile_gcs.c
gcc -Wall -g -O2 -I. -fPIC -c -o hfile_s3.o hfile_s3.c
ar -rc libhts.a kfunc.o knetfile.o kstring.o bcf_sr_sort.o bgzf.o errmod.o faidx.o hfile.o hfile_net.o hts.o hts_os.o md5.o multipart.o probaln.o realn.o regidx.o sam.o synced_bcf_reader.o vcf_sweep.o tbx.o textutils.o thread_pool.o vcf.o vcfutils.o cram/cram_codecs.o cram/cram_decode.o cram/cram_encode.o cram/cram_external.o cram/cram_index.o cram/cram_io.o cram/cram_samtools.o cram/cram_stats.o cram/files.o cram/mFILE.o cram/open_trace_file.o cram/pooled_alloc.o cram/rANS_static.o cram/sam_header.o cram/string_alloc.o  hfile_libcurl.o hfile_gcs.o hfile_s3.o
ranlib libhts.a
gcc -dynamiclib -install_name /usr/local/lib/libhts.2.dylib -current_version 1.9 -compatibility_version 2   -o libhts.dylib kfunc.o knetfile.o kstring.o bcf_sr_sort.o bgzf.o errmod.o faidx.o hfile.o hfile_net.o hts.o hts_os.o md5.o multipart.o probaln.o realn.o regidx.o sam.o synced_bcf_reader.o vcf_sweep.o tbx.o textutils.o thread_pool.o vcf.o vcfutils.o cram/cram_codecs.o cram/cram_decode.o cram/cram_encode.o cram/cram_external.o cram/cram_index.o cram/cram_io.o cram/cram_samtools.o cram/cram_stats.o cram/files.o cram/mFILE.o cram/open_trace_file.o cram/pooled_alloc.o cram/rANS_static.o cram/sam_header.o cram/string_alloc.o  hfile_libcurl.o hfile_gcs.o hfile_s3.o -lz   -lcurl 
ln -sf libhts.dylib libhts.2.dylib
gcc -Wall -g -O2 -I. -fPIC -c -o bgzip.o bgzip.c
gcc   -o bgzip bgzip.o libhts.a -lz   -lcurl  -lpthread
gcc -Wall -g -O2 -I. -fPIC -c -o htsfile.o htsfile.c
gcc   -o htsfile htsfile.o libhts.a -lz   -lcurl  -lpthread
gcc -Wall -g -O2 -I. -fPIC -c -o tabix.o tabix.c
gcc   -o tabix tabix.o libhts.a -lz   -lcurl  -lpthread
gcc -Wall -g -O2 -I. -fPIC -c -o test/hts_endian.o test/hts_endian.c
gcc   -o test/hts_endian test/hts_endian.o -lz   -lcurl 
gcc -Wall -g -O2 -I. -fPIC -c -o test/fieldarith.o test/fieldarith.c
gcc   -o test/fieldarith test/fieldarith.o libhts.a -lz   -lcurl  -lpthread
gcc -Wall -g -O2 -I. -fPIC -c -o test/hfile.o test/hfile.c
gcc   -o test/hfile test/hfile.o libhts.a -lz   -lcurl  -lpthread
gcc -Wall -g -O2 -I. -fPIC -c -o test/sam.o test/sam.c
gcc   -o test/sam test/sam.o libhts.a -lz   -lcurl  -lpthread
gcc -Wall -g -O2 -I. -fPIC -c -o test/test_bgzf.o test/test_bgzf.c
gcc   -o test/test_bgzf test/test_bgzf.o libhts.a -lz -lz   -lcurl  -lpthread
gcc -Wall -g -O2 -I. -fPIC -c -o test/test_realn.o test/test_realn.c
gcc   -o test/test_realn test/test_realn.o libhts.a -lz   -lcurl  -lpthread
gcc -Wall -g -O2 -I. -fPIC -c -o test/test-regidx.o test/test-regidx.c
gcc   -o test/test-regidx test/test-regidx.o libhts.a -lz   -lcurl  -lpthread
gcc -Wall -g -O2 -I. -fPIC -c -o test/test_view.o test/test_view.c
gcc   -o test/test_view test/test_view.o libhts.a -lz   -lcurl  -lpthread
gcc -Wall -g -O2 -I. -fPIC -c -o test/test-vcf-api.o test/test-vcf-api.c
gcc   -o test/test-vcf-api test/test-vcf-api.o libhts.a -lz   -lcurl  -lpthread
gcc -Wall -g -O2 -I. -fPIC -c -o test/test-vcf-sweep.o test/test-vcf-sweep.c
gcc   -o test/test-vcf-sweep test/test-vcf-sweep.o libhts.a -lz   -lcurl  -lpthread
gcc -Wall -g -O2 -I. -fPIC -c -o test/test-bcf-sr.o test/test-bcf-sr.c
gcc   -o test/test-bcf-sr test/test-bcf-sr.o libhts.a -lz -lz   -lcurl  -lpthread
gcc -Wall -g -O2 -I. -fPIC -c -o test/test-bcf-translate.o test/test-bcf-translate.c
gcc   -o test/test-bcf-translate test/test-bcf-translate.o libhts.a -lz -lz   -lcurl  -lpthread
gcc -std=c99 -O3 -Wall -Wno-unused-function -fPIC -shared  -o ctg_cns.so bseq.c align.c bsort.c dag.c ctg_cns.c htslib//libhts.a -D_SVID_SOURCE -DLGS_CORRECT -I ./htslib/ -lm -lpthread -lz  
Undefined symbols for architecture arm64:
  "_curl_easy_cleanup", referenced from:
      _libcurl_open in libhts.a(hfile_libcurl.o)
      _libcurl_close in libhts.a(hfile_libcurl.o)
      _restart_from_position in libhts.a(hfile_libcurl.o)
  "_curl_easy_duphandle", referenced from:
      _restart_from_position in libhts.a(hfile_libcurl.o)
  "_curl_easy_getinfo", referenced from:
      _easy_errno in libhts.a(hfile_libcurl.o)
      _libcurl_open in libhts.a(hfile_libcurl.o)
  "_curl_easy_init", referenced from:
      _libcurl_open in libhts.a(hfile_libcurl.o)
  "_curl_easy_pause", referenced from:
      _libcurl_read in libhts.a(hfile_libcurl.o)
      _libcurl_write in libhts.a(hfile_libcurl.o)
      _libcurl_close in libhts.a(hfile_libcurl.o)
      _restart_from_position in libhts.a(hfile_libcurl.o)
  "_curl_easy_reset", referenced from:
      _restart_from_position in libhts.a(hfile_libcurl.o)
  "_curl_easy_setopt", referenced from:
      _libcurl_open in libhts.a(hfile_libcurl.o)
      _restart_from_position in libhts.a(hfile_libcurl.o)
  "_curl_global_cleanup", referenced from:
      _hfile_plugin_init_libcurl in libhts.a(hfile_libcurl.o)
      _libcurl_exit in libhts.a(hfile_libcurl.o)
  "_curl_global_init", referenced from:
      _hfile_plugin_init_libcurl in libhts.a(hfile_libcurl.o)
  "_curl_multi_add_handle", referenced from:
      _libcurl_open in libhts.a(hfile_libcurl.o)
      _restart_from_position in libhts.a(hfile_libcurl.o)
  "_curl_multi_cleanup", referenced from:
      _libcurl_open in libhts.a(hfile_libcurl.o)
      _libcurl_close in libhts.a(hfile_libcurl.o)
  "_curl_multi_fdset", referenced from:
      _wait_perform in libhts.a(hfile_libcurl.o)
  "_curl_multi_info_read", referenced from:
      _wait_perform in libhts.a(hfile_libcurl.o)
  "_curl_multi_init", referenced from:
      _libcurl_open in libhts.a(hfile_libcurl.o)
  "_curl_multi_perform", referenced from:
      _wait_perform in libhts.a(hfile_libcurl.o)
  "_curl_multi_remove_handle", referenced from:
      _libcurl_open in libhts.a(hfile_libcurl.o)
      _libcurl_close in libhts.a(hfile_libcurl.o)
      _restart_from_position in libhts.a(hfile_libcurl.o)
  "_curl_multi_timeout", referenced from:
      _wait_perform in libhts.a(hfile_libcurl.o)
  "_curl_share_cleanup", referenced from:
      _hfile_plugin_init_libcurl in libhts.a(hfile_libcurl.o)
      _libcurl_exit in libhts.a(hfile_libcurl.o)
  "_curl_share_init", referenced from:
      _hfile_plugin_init_libcurl in libhts.a(hfile_libcurl.o)
  "_curl_share_setopt", referenced from:
      _hfile_plugin_init_libcurl in libhts.a(hfile_libcurl.o)
  "_curl_version_info", referenced from:
      _hfile_plugin_init_libcurl in libhts.a(hfile_libcurl.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [ctg_cns.so] Error 1
make: *** [all] Error 2
</pre>

**Comment by moold** [comment]
I don't test NextDenovo on a macOS system, but it seems these errors were casued by `minimap2` and `htslib`.
For  `minimap2`, you can try (from the Users' Guide of `minimap2`):
```
Minimap2 also works with ARM CPUs supporting the NEON instruction sets. To compile for 32 bit ARM architectures (such as ARMv7), use make arm_neon=1. To compile for for 64 bit ARM architectures (such as ARMv8), use make arm_neon=1 aarch64=1.
```

**Comment by ianaebutler** [comment]
Thanks for your response. I just switched to a Linux machine so I don't have to deal with this. The test data is working now, but I am getting an error with my data. I will open a new issue for that since it is a different problem.
