### ISSUE TITLE
Can you run nextDenovo without a config file?

### ISSUE THREAD

**Issue by JWDebler** [Nextomics/NextDenovo#178]
**Question or Expected behavior**
Is it possible to run nextDenovo without a config file and instead supply all the options as via the command line?
I want to automate assemblies as much as possible and therefore prefer to supply options via commandline flags instead of generating config and fofn files.
Cheers

**Operating system**
Ubuntu 18.04.6 LTS

**NextDenovo**
2.5.2

**Comment by moold** [comment]
No, for the current version. But,  we are working on NextDenovo2 that can accept options via commandline.
