### ISSUE TITLE
No assembly file after running NextDenovo

### ISSUE THREAD

**Issue by RacheliHadjez** [Nextomics/NextDenovo#184]
Hello,
I ran NextDenovo on a 60m sized genome and it ran for a few hours but I did not get an assembly file.

This is the command I used:
#!/bin/bash
#PBS -q huchond
#PBS -o out_Assemble_Nextdenovo_HSA
#PBS -e err_Assemble_Nextdenovo_HSA
#PBS -l nodes=compute-0-60:ppn=250
#PBS -r y

module load Python-3.10.2
module load NextDenovo-2.5.2

nextDenovo /dorotheeh/hadjez/NextDenovo_cfg_HSA.cfg -b -l LOG_HSA_Nextdenovo.txt

What version of GCC are you using?
4.8.5

What version of Python are you using?
3.10.2

What version of NextDenovo are you using? 
2.5.2

This is the error file I am getting:
[NextDenovoError.txt](https://github.com/Nextomics/NextDenovo/files/11756129/NextDenovoError.txt)

Thank you!!!

**Comment by moold** [comment]
As the log says:
```
[174109 INFO] 2023-06-14 11:56:30 nextDenovo finished
[174109 INFO] 2023-06-14 11:56:30 final assembly file:
[174109 INFO] 2023-06-14 11:56:30 [35m /dorotheeh/hadjez/NextDenovo_HSA/03.ctg_graph/nd.asm.fasta [0m
[174109 INFO] 2023-06-14 11:56:30 final stat file:
[174109 INFO] 2023-06-14 11:56:30 [35m /dorotheeh/hadjez/NextDenovo_HSA/03.ctg_graph/nd.asm.fasta.stat [0m
[174109 INFO] 2023-06-14 11:56:30 asm stat:
[174109 INFO] 2023-06-14 11:56:30 
Type           Length (bp)            Count (#)
N10              8023315                   1
N20              5372645                   3
N30              4668152                   4
N40              3402517                   6
N50              2258397                   9
N60              2148079                  12
N70              1796393                  16
N80              1221106                  21
N90               488771                  30

Min.               25907                   -
Max.             8023315                   -
Ave.              787407                   -
Total           74803720                  95
```
