### ISSUE TITLE
Does NEXTDENOVO filter the contig before output?

### ISSUE THREAD

**Issue by cfz1998** [Nextomics/NextDenovo#189]
**Question or Expected behavior**
Hi! @moold 
I have used `nextdenovo` and `hifiasm` for my HIFI reads.
`nextdenovo` has 14 contigs, but `hifiasm` has 44 (shorter).

Does NEXTDENOVO filter the contig(base contig length) before output?

**Comment by moold** [comment]
NO

**Comment by cfz1998** [comment]
Thank you for your reply!
