### ISSUE TITLE
A problem I met when running NextDenovo

### ISSUE THREAD

**Issue by zjwang0831** [Nextomics/NextDenovo#19]
Hi!
I ran the test example(the command is `nohup nextDenovo test/run.cfg &` )
Here is run.cfg file:
```
[General]
job_type = local
job_prefix = nextDenovo
task = all # 'all', 'correct', 'assemble'
rewrite = yes # yes/no
deltmp = yes
rerun = 3
parallel_jobs = 2
input_type = raw
input_fofn = ./input.fofn
workdir = ./01_rundir

[correct_option]
read_cutoff = 1k
seed_cutoff = 32k
blocksize = 1g
pa_correction = 2
seed_cutfiles = 2
sort_options = -m 1g -t 2 -k 50
minimap2_options_raw = -x ava-ont -t 8
correction_options = -p 15

[assemble_option]
random_round = 10
minimap2_options_cns = -x ava-ont -t 8 -k17 -w17
nextgraph_options = -a 1
```
But I got error like this:
```
[INFO] 2019-10-21 17:04:16,871 start...
[INFO] 2019-10-21 17:04:16,871 logfile: pid111095.log.info
[WARNING] 2019-10-21 17:04:16,872 Re-write workdir
[INFO] 2019-10-21 17:04:16,872 options: 
[INFO] 2019-10-21 17:04:16,873 {'sort_threads': 2, 'nodelist': '', 'rewrite': 1, 'blocksize': '1g', 'job_prefix': 'nextDenovo', 'job_type': 'local', 'minimap2_options_raw': '-x ava-ont -t 8', 'cns_threads': 15, 'sort_mem': '1g', 'seed_cutoff': '32000', 'input_fofn': '/h
[INFO] 2019-10-21 17:04:16,873 skip mkdir: /home/lailab/wangzijian/software/NextDenovo/test_data/./01_rundir
[INFO] 2019-10-21 17:04:16,873 skip mkdir: /home/lailab/wangzijian/software/NextDenovo/test_data/./01_rundir/01.raw_align
[INFO] 2019-10-21 17:04:16,873 skip mkdir: /home/lailab/wangzijian/software/NextDenovo/test_data/./01_rundir/02.cns_align
[INFO] 2019-10-21 17:04:16,873 skip mkdir: /home/lailab/wangzijian/software/NextDenovo/test_data/./01_rundir/03.ctg_graph
[INFO] 2019-10-21 17:04:16,874 analysis tasks done
[INFO] 2019-10-21 17:04:16,874 total jobs: 1
[INFO] 2019-10-21 17:04:16,876 Throw jobID:[111096] jobCmd:[/home/lailab/wangzijian/software/NextDenovo/test_data/01_rundir/01.raw_align/01.db_split.sh.work/db_split0/nextDenovo.sh] in the local_cycle.
[ERROR] 2019-10-21 17:04:17,400 db_split failed: please check the following logs:
[ERROR] 2019-10-21 17:04:17,400 /home/lailab/wangzijian/software/NextDenovo/test_data/01_rundir/01.raw_align/01.db_split.sh.work/db_split0/nextDenovo.sh.e
```
Then I checked  `/home/lailab/wangzijian/software/NextDenovo/test_data/01_rundir/01.raw_align/01.db_split.sh.work/db_split0/nextDenovo.sh.e` to find out what is the error , which is shown below:
```
hostname
+ hostname
cd /home/lailab/wangzijian/software/NextDenovo/test_data/01_rundir/01.raw_align/01.db_split.sh.work/db_split0
+ cd /home/lailab/wangzijian/software/NextDenovo/test_data/01_rundir/01.raw_align/01.db_split.sh.work/db_split0
time /home/lailab/wangzijian/software/NextDenovo/bin/seq_dump -f 1k -s 32000 -b 1g -n 2 -d /home/lailab/wangzijian/software/NextDenovo/test_data/01_rundir/01.raw_align /home/lailab/wangzijian/software/NextDenovo/test_data/input.fofn
+ time /home/lailab/wangzijian/software/NextDenovo/bin/seq_dump -f 1k -s 32000 -b 1g -n 2 -d /home/lailab/wangzijian/software/NextDenovo/test_data/01_rundir/01.raw_align /home/lailab/wangzijian/software/NextDenovo/test_data/input.fofn
/home/lailab/wangzijian/software/NextDenovo/test_data/01_rundir/01.raw_align/01.db_split.sh.work/db_split0/nextDenovo.sh: 5: /home/lailab/wangzijian/software/NextDenovo/test_data/01_rundir/01.raw_align/01.db_split.sh.work/db_split0/nextDenovo.sh: time: not found 
```

Could you tell me how to deal with it? Thanks a lot!

**Comment by moold** [comment]
Could  you try to run the command `time` or `/usr/bin/time` ?

**Comment by zjwang0831** [comment]
I tried `which time`,`time`and `/usr/bin/time` . There is a `time` somewhere but it seems that the system doesn't know where it is, neither do I.
```
(py27) lailab@debian-07:~/wangzijian/software/NextDenovo$ which time
(py27) lailab@debian-07:~/wangzijian/software/NextDenovo$ time ls
README.md  bin	doc  lib  minimap2  nextDenovo	nohup.out  pid109778.log.info  pid111095.log.info  test_data

real	0m0.002s
user	0m0.000s
sys	0m0.000s
(py27) lailab@debian-07:~/wangzijian/software/NextDenovo$ /usr/bin/time ls
-bash: /usr/bin/time: No such file or directory
```

**Comment by moold** [comment]
It seems your system already includes the `time` command? so could you try to run command `time /home/lailab/wangzijian/software/NextDenovo/bin/seq_dump -f 1k -s 32000 -b 1g -n 2 -d /home/lailab/wangzijian/software/NextDenovo/test_data/01_rundir/01.raw_align /home/lailab/wangzijian/software/NextDenovo/test_data/input.fofn` manually?

**Comment by zjwang0831** [comment]
The system found `time` when I ran `time` directly, while the system cannot when I ran in the background.
```
(py27) lailab@debian-07:~/wangzijian/software/NextDenovo$ nohup time /home/lailab/wangzijian/software/NextDenovo/bin/seq_dump -f 1k -s 32000 -b 1g -n 2 -d /home/lailab/wangzijian/software/NextDenovo/test_data/01_rundir/01.raw_align /home/lailab/wangzijian/software/NextDenovo/test_data/input.fofn  &
[1] 74494
(py27) lailab@debian-07:~/wangzijian/software/NextDenovo$ nohup: ignoring input and appending output to 'nohup.out'
nohup: failed to run command 'time': No such file or directory

[1]+  Exit 127                nohup time /home/lailab/wangzijian/software/NextDenovo/bin/seq_dump -f 1k -s 32000 -b 1g -n 2 -d /home/lailab/wangzijian/software/NextDenovo/test_data/01_rundir/01.raw_align /home/lailab/wangzijian/software/NextDenovo/test_data/input.fofn
```
```
(py27) lailab@debian-07:~/wangzijian/software/NextDenovo$ time /home/lailab/wangzijian/software/NextDenovo/bin/seq_dump -f 1k -s 32000 -b 1g -n 2 -d /home/lailab/wangzijian/software/NextDenovo/test_data/01_rundir/01.raw_align /home/lailab/wangzijian/software/NextDenovo/test_data/input.fofn

real	0m0.091s
user	0m0.080s
sys	0m0.012s
```

**Comment by moold** [comment]
Hi, if you still have this problem, I have an alternative unfriendly method you can try. Change line 138 `subtask += 'time ' + task + '\n'` in file `lib/task_control.py` to `subtask += task + '\n'`, It maybe work.

**Comment by zjwang0831** [comment]
I login the server as root, and install a `time` , it works know. Thanks for helping!

**Comment by moold** [comment]
ok

**Comment by Vaibhav180997** [comment]
[erorr_814_pid184203.log.info.txt](https://github.com/user-attachments/files/18253071/erorr_814_pid184203.log.info.txt)
run.cfg file details -

rerun:                        3
task:                         all
deltmp:                       1
rewrite:                      1
read_type:                    ont
job_type:                     local
input_type:                   raw
read_cutoff:                  1k
parallel_jobs:                4
pa_correction:                2
seed_cutfiles:                3
seed_depth:                   39.71
genome_size:                  650MB
seed_cutoff:                  10000
blocksize:                    3585829702
job_prefix:                   nextDenovo
ctg_cns_options:              -p 15
nextgraph_options:            -a 1
sort_options:                 -m 1g -t 2 -k 40
minimap2_options_map:         -x map-ont
minimap2_options_raw:         -t 12 -x ava-ont
input_fofn:                   /home/samir/VT/NextDenovo/Ag_new23dec/./input.fofn
workdir:                      /home/samir/VT/NextDenovo/Ag_new23dec/./outputFinalAg814
correction_options:           -p 15 -max_lq_length 10000 -r ont -min_len_seed 5000
minimap2_options_cns:         -t 12 -x ava-ont -k 17 -w 17 --minlen 1000 --maxhan1 5000
raw_aligndir:                 /home/samir/VT/NextDenovo/Ag_new23dec/./outputFinalAg814/01.raw_align
cns_aligndir:                 /home/samir/VT/NextDenovo/Ag_new23dec/./outputFinalAg814/02.cns_align
ctg_graphdir:                 /home/samir/VT/NextDenovo/Ag_new23dec/./outputFinalAg814/03.ctg_graph
error phasing in pid log file .
[40741 CRITICAL] 2024-12-23 20:14:52 Command '/bin/bash /home/samir/VT/NextDenovo/Ag_new23dec/outputFinalAg814/01.raw_align/03.raw_align.sh.work/raw_align12/nextDenovo.sh > /home/samir/VT/NextDenovo/Ag_new23dec/outputFinalAg814/01.raw_align/03.raw_align.sh.work/raw_align12/nextDenovo.sh.o 2> /home/samir/VT/NextDenovo/Ag_new23dec/outputFinalAg814/01.raw_align/03.raw_align.sh.work/raw_align12/nextDenovo.sh.e' returned non-zero exit status 1, error info: .
[184203 ERROR] 2024-12-23 20:14:54 raw_align failed: please check the following logs:
[184203 ERROR] 2024-12-23 20:14:54 /home/samir/VT/NextDenovo/Ag_new23dec/outputFinalAg814/01.raw_align/03.raw_align.sh.work/raw_align01/nextDenovo.sh.e
