### ISSUE TITLE
hello , i used the nextdenovo to assemble the ultra large size genome of 23g, the fq only 270g, just want to assemble the grapgh

### ISSUE THREAD

**Issue by Jiangjiangzhang6** [Nextomics/NextDenovo#199]
![image](https://github.com/Nextomics/NextDenovo/assets/101324838/bf8eeaeb-3a00-44e0-a38d-60f066ab5d75)

th data was ont ultra long benyond 100kb
but the error show the 
![image](https://github.com/Nextomics/NextDenovo/assets/101324838/da14aae2-dd92-4552-9f83-8c1e282500af)
if  I didnot want to add the ont data , just want to get some grapgh, how to do this

**Comment by Jiangjiangzhang6** [comment]
looking forward to your reply

**Comment by moold** [comment]
I think you can set the `genome_size` to a smaller value.

**Comment by Jiangjiangzhang6** [comment]
> I think you can set the `genome_size` to a smaller value.

i set 6g, but the error show not enough for assembly

**Comment by moold** [comment]
set `rewrite=no` or rerun in a new work directory

**Comment by Jiangjiangzhang6** [comment]
> set `rewrite=no` or rerun in a new work directory

途中的报错就是我跑出来的，

**Comment by Jiangjiangzhang6** [comment]
> set `rewrite=no` or rerun in a new work directory

或者我加您个微信，您应该是武汉未来组的吧，

**Comment by Jiangjiangzhang6** [comment]
???没解决啊
