### ISSUE TITLE
How to improve the N50 and reduce contigs numbers?

### ISSUE THREAD

**Issue by cj2jy** [Nextomics/NextDenovo#200]
**Question or Expected behavior**
A clear and concise description of your question or what you expected to happen.

**Operating system**
Which operating system and version are you using?
You can use the command `lsb_release -a` to get it.

**GCC**
What version of GCC are you using?
You can use the command `gcc -v` to get it.

**Python**
What version of Python are you using?
You can use the command `python --version` to get it.

**NextDenovo**
What version of NextDenovo are you using?
You can use the command `nextDenovo -v` to get it.

**Additional context** (Optional)

**Comment by moold** [comment]
It's hard to say, if I had a better solution I would set it as the default value. How ever, I think you can try to optimize these parameters: `seed_cutoff`, `-k -w -f` in `minimap2_options_raw` and `minimap2_options_cns`. BTW, you should make sure you are using the latest version of `NextDenovo`. You also can sequencing more ultra-long ONT SUP reads. At the last, you can try some other assemblers.

**Comment by cj2jy** [comment]
Thank you, I will change those parameters and try again. But I don't know what the **-f** means and how to optimize it, do you have any suggestion?

**Comment by moold** [comment]
try `-f 0.0001` or less

**Comment by cj2jy** [comment]
Thank you, I ran again and it is still running. Can I use my last assembly result **nd.asm.fasta** as input to run assemble again? Would that be a better result?

**Comment by cj2jy** [comment]
Thank you, I ran again and it is still running. Can I use my last assembly result **nd.asm.fasta** as input to run assemble again? Would that be a better result?

**Comment by moold** [comment]
No

**Comment by DaniPaulo** [comment]
Hi @cj2jy, 
I'm still trying to understand how to run NextDenovo using SLURM. Could you share your `script.slurm.sh`?

In the `run.cfg` you set `submit = sbatch --cpus-per-task=20 --mem-per-cpu=4g`, so that means you also set `#SBATCH --cpus-per-task=20` and `#SBATCH --mem-per-cpu=4g`?
