### ISSUE TITLE
Test won't run

### ISSUE THREAD

**Issue by JWrighty97** [Nextomics/NextDenovo#201]
**Describe the bug**
A clear and concise description of what the bug or error is.

When I try to execute nextDenovo on test_data/run.cfg the nextDenovo command is not found. 
The file has been downloaded and openable with nano nextDenovo however does not seem to be working. 

I have tried two separate downloads, from the link and importing from Git however neither seem to leave me with an executable file. 

Is there anything you would suggest?

**Operating system**
Which operating system and version are you using?
You can use the command `lsb_release -a` to get it.

MacOS 

**GCC**
What version of GCC are you using?
You can use the command `gcc -v` to get it.

Apple clang version 15.0.0 (clang-1500.1.0.2.5)

**Python**
What version of Python are you using?
You can use the command `python --version` to get it.

Python 3.12.2

**Comment by moold** [comment]
If you install NextDenovo to this directory: `path_to_nextDenovo`, then try `path_to_nextDenovo/nextDenovo test_data/run.cfg`
