### ISSUE TITLE
assembly problem

### ISSUE THREAD

**Issue by yao-chenxin** [Nextomics/NextDenovo#208]
Humblest greetings;
My understanding of V2.5.0 and above is that it can perform genome assembly of more than 10G, should this be OK?
At present, I am assembling 5g genome, and 100 Tb data cache is generated in step 01.raw_align, which I think is abnormal. Do you have any suggestions to help solve it?
Looking forward to hearing from you!

**Comment by moold** [comment]
Yes, the result size depends on repeat content and genome size, so if the log shows no errors, that's fine.

**Comment by yao-chenxin** [comment]
ok，
Thank you very much for your reply.
