### ISSUE TITLE
Corrected reads file for running wtdbg

### ISSUE THREAD

**Issue by Renshengjie** [Nextomics/NextDenovo#216]
Hello Dr. Hu,

I want to runnning Nextdenovo correction data for WTDBG assembly. The raw data is pacbio clr of 210 Gb for ~87 depth sequence (genome size 2.4g). Currently, I finished correction process:

##  [297336 INFO] 2024-10-18 11:16:39  /mnt/d/all/./01_rundir/02.cns_align/01.seed_cns.sh.work/seed_cns*/cns.fasta

However, I only get 33 gb crorrection sequences for 5 cns.fasta files at 02.cns_align\01.seed_cns.sh.work.

Does this nomal for the next step assembly?

Thank you!

**Comment by moold** [comment]
Use `-b` in [correction_options](https://nextdenovo.readthedocs.io/en/latest/OPTION.html#cmdoption-arg-correction_options) if you want to use other assmblers to do the assembly.

**Comment by Renshengjie** [comment]
Thanks for your suggestion. Would be the correction results (33 gb correction sequences) appropriate for complete the nextDenovo assembly. Currently, the NextDenovo program is still running.

**Comment by moold** [comment]
yes

**Comment by Renshengjie** [comment]
Thanks. 
Have a great day!
