### ISSUE TITLE
The input data is insufficient for an assembly

### ISSUE THREAD

**Issue by laomaizi-beagle** [Nextomics/NextDenovo#217]
I can not run NextDenovo Properly
[Read length stat]
Types            Count (#) Length (bp)
N10                      1   15755
N20                      1       0
N30                      0       0
N40                      0       0
N50                      0       0
N60                      0       0
N70                      0       0
N80                      0       0
N90                      0       0

Types               Count (#)           Bases (bp)  Depth (X)
Raw                         6                15755       0.00
Filtered                    5                    0       0.00
Clean                       1                15755       0.00

*Suggested seed_cutoff (genome size: 4500.00Mb, expected seed depth: 45, real seed depth: 0.00): 15755 bp
[79909 ERROR] 2024-11-05 14:16:18 the input data is insufficient for an assembly.
  

and my cfg file is :
job_type = sge
job_prefix = nextDenovo
task = all
rewrite = yes
deltmp = yes
parallel_jobs = 20
input_type = raw
read_type = clr
input_fofn = input.fofn
workdir = minshan
cluter_options = auto

[correct_option]
read_cutoff = 1k
seed_cutoff = 0
genome_size = 4.5g
pa_correction = 20
seed_cutfiles = 20
sort_options = -m 40g -t 8 -k 40
minimap2_options_raw = -t 8
correction_options = -p 8

[assemble_option]
minimap2_options_cns = -t 8 -x ava-pb
nextgraph_options = -a 1

**Comment by laomaizi-beagle** [comment]
dear author ,how can I solve this issue

**Comment by moold** [comment]
check the input file: ` input.fofn`, `NextDenovo` only read one read.

**Comment by laomaizi-beagle** [comment]
dear author ,
thank you for your suggestions,but I just put one file in NextDenovo, I put a BAM file in my input.fofn which is m64081_220128_153815.subreads.bam    I am looking forward to your suggestions.    Thank you very much

**Comment by moold** [comment]
`NextDenovo` can only accept fasta/fastq files, so you need to convert your bam file to fasta/fastq file, you can use `samtools fasta/fastq`.

**Comment by laomaizi-beagle** [comment]
thank you very much, and i will try later
