### ISSUE TITLE
Too low corrected base rate

### ISSUE THREAD

**Issue by Renshengjie** [Nextomics/NextDenovo#219]
Dear Dr. Hu,

The ratio of the size of the corrected reads to the size of the raw reads to be corrected is too low.

**Error message**
I use NextDevova for Pacbio CLR raw sequence assembly, for 216 GB raw reads only generated 15Gb final corrected reads at file of (02.cns_align/01.seed_cns.sh.work/seed_cns*/cns.fasta). This is much lower compared with average 83% to 97% correated bases rate in your publiaction (Hu et al. Genome Biology (2024) 25:107). 

**Genome characteristics**
2.4 GB

**Input data**
`Total base count: 216 gb, sequencing depth: 90, average/N50 read length: 21kb.

**run file**
job_type = local
job_prefix = nextDenovo
task = all # 'all', 'correct', 'assemble'
rewrite = yes # yes/no
deltmp = yes
rerun = 3
parallel_jobs = 3
input_type = raw
read_type = clr # clr, ont, hifi
input_fofn = ./input.fofn
workdir = ./01_rundir

[correct_option]
read_cutoff = 1k
genome_size = 2.4g # estimated genome size
seed_cutoff = 36k
blocksize = 3g
pa_correction = 4
seed_cutfiles = 4
sort_options = -m 50g -t 10 -k 45
minimap2_options_raw = -x ava-pb -t 12
correction_options = -p 20

[assemble_option]
minimap2_options_cns = -x ava-pb -t 12 -k17 -w17
nextgraph_options = -a 1

**NextDenovo**
(version:2.5.2)

**Comment by moold** [comment]
see #216

**Comment by Renshengjie** [comment]
Thanks for your advice. 
 Do you mean changed the "correction_options = -p 20" into "correction_options = -b 20"?
I have been tried this parameter, however the input file would not run.
Cheers

**Comment by moold** [comment]
correction_options = -b -p 20

**Comment by Renshengjie** [comment]
Thanks.
Have a great day!

**Comment by Renshengjie** [comment]
Still only get 24 GB correction data for adding "correction_options =-b -p 20" ， would be any other suggestions?
run file
job_type = local
job_prefix = nextDenovo
task = all # 'all', 'correct', 'assemble'
rewrite = yes # yes/no
deltmp = yes
rerun = 3
parallel_jobs = 3
input_type = raw
read_type = clr # clr, ont, hifi
input_fofn = ./input.fofn
workdir = ./01_rundir

[correct_option]
read_cutoff = 1k
genome_size = 2.4g # estimated genome size
seed_cutoff = 36k
blocksize = 3g
pa_correction = 4
seed_cutfiles = 4
sort_options = -m 50g -t 10 -k 45
minimap2_options_raw = -x ava-pb -t 12
correction_options =-b -p 20

[assemble_option]
minimap2_options_cns = -x ava-pb -t 12 -k17 -w17
nextgraph_options = -a 1

NextDenovo
(version:2.5.2)

**Comment by moold** [comment]
try reducing `seed_cutoff = 36k`, because `nextdenovo` only correct reads with length >= seed_cutoff.

**Comment by Renshengjie** [comment]
Thanks. I have running the new parameters.
Look forward to the new results!

Cheers

**Comment by Renshengjie** [comment]
Dear Dr. Hu,
I adjust seed_cutoff parameters "seed_cutoff = 1200", and generated 90 GB correction reads (raw clr reads 200Gb, genome size=2.5 gb). I think this correction rates is still much lower compared with your publication for 83% to 95% correction rates. Would you think it is normal or this data is enough for completing next step assembly task? 
Thanks for your kind help.
Cheers

**Comment by moold** [comment]
The `seed_cutoff` is too short, by default, NextDenovo is optimized for assembly/error-correction with seed_cutoff >= 10kb, see [here](https://nextdenovo.readthedocs.io/en/latest/QSTART.html#limitations), so its internal parameters will filter out very short reads. If you want to caculate the erro-correction rate, you need to set  `seed_cutoff > 10kb` and use `correction_options =-b ...`.  
If you just want to to do the assmebly by nextDenovo, you need to try the defaut parameters first.

**Comment by Renshengjie** [comment]
Hi Dr. Hu,
It seems the size of corrections reads is not significant impact for "seed_cutoff = 1200". Here is the sum of statistics: 
Types            Count (#) Length (bp)
N10                 202510   39336
N20                 467116   32826
N30                 782374   27573
N40                1156669   23271
N50                1600803   19560
N60                2132072   16241
N70                2779207   13156
N80                3597162   10117
N90                4724320    6811.

My questions are (1) for the current correction reads (~ 40 depth vs genome size=2.4gb) would be appropriate for the next assembly task? (2) I noticed your publication at Genome Biollogy achieves correctdon reads rates 83% to 95%, while I just get around 50%, do you have advices?
