### ISSUE TITLE
Ask help for software usage

### ISSUE THREAD

**Issue by panbei123** [Nextomics/NextDenovo#22]
Dear Hu,
   Thanks for your update of nextDoneov v2.0. 
   However,  I'm not sure if I need to change the parameter in demo file run.cfg when I run test data. Because  there are some errors when I run  test data based on demo run.cfg file.
  After check final results step by step, there were two files listed in  01.ctg_graph.input.seqs. And I got the empty result file nextgraph.assembly.contig.fasta  run bellow comment:
"nextgraph -a 1 -f 01.ctg_graph.input.seqs  01.ctg_graph.input.ovls -o nextgraph.assembly.contig.fasta" 
  I'm not sure which step emerged error. And why I couldn't run test data successfuly. Please the process file and log file as bellow.
 Please help me debug this problem. Many thanks for your help!
Best wishes.

**Comment by panbei123** [comment]
[INFO] 2019-10-29 10:59:07,431 start...
[INFO] 2019-10-29 10:59:07,433 logfile: pid31317.log.info
[WARNING] 2019-10-29 10:59:07,437 Re-write workdir
[INFO] 2019-10-29 10:59:07,437 options: 
[INFO] 2019-10-29 10:59:07,437 {'sort_threads': 2, 'nodelist': '', 'rewrite': 1, 'blocksize': '1g', 'job_prefix': 'nextDenovo', 'job_type': 'local', 'minimap2_options_raw': '-x ava-ont -t 8', 'cns_threads': 15, 'sort_mem': '1g', 'seed_cutoff': '32000', 'input_fofn': '/mnt/ilustre/centos7users/name/Training/Nextdenovo/test_nextDenovo/./input.fofn', 'read_cutoff': '1k', 'input_type': 'raw', 'sort_options': '-m 1g -t 2 -k 50', 'parallel_jobs': '2', 'cluster_options': '', 'ctg_graphdir': '/mnt/ilustre/centos7users/name/Training/Nextdenovo/test_nextDenovo/./01_rundir/03.ctg_graph', 'pa_correction': '2', 'workdir': '/mnt/ilustre/centos7users/name/Training/Nextdenovo/test_nextDenovo/./01_rundir', 'random_round': '10', 'minimap2_threads': (8, 8), 'minimap2_options_cns': '-x ava-ont -t 8 -k17 -w17', 'cns_aligndir': '/mnt/ilustre/centos7users/name/Training/Nextdenovo/test_nextDenovo/./01_rundir/02.cns_align', 'seed_cutfiles': '2', 'raw_aligndir': '/mnt/ilustre/centos7users/name/Training/Nextdenovo/test_nextDenovo/./01_rundir/01.raw_align', 'task': 'all', 'deltmp': 1, 'rerun': 3, 'correction_options': '-p 15 -max_lq_length 10000', 'nextgraph_options': '-a 1'}
[INFO] 2019-10-29 10:59:07,438 mkdir: /mnt/ilustre/centos7users/sname/Training/Nextdenovo/test_nextDenovo/./01_rundir
[INFO] 2019-10-29 10:59:07,439 mkdir: /mnt/ilustre/centos7users/name/Training/Nextdenovo/test_nextDenovo/./01_rundir/01.raw_align
[INFO] 2019-10-29 10:59:07,439 mkdir: /mnt/ilustre/centos7users/name/Training/Nextdenovo/test_nextDenovo/./01_rundir/02.cns_align
[INFO] 2019-10-29 10:59:07,440 mkdir: /mnt/ilustre/centos7users/name/Training/Nextdenovo/test_nextDenovo/./01_rundir/03.ctg_graph
[INFO] 2019-10-29 10:59:07,443 analysis tasks done
[INFO] 2019-10-29 10:59:07,446 total jobs: 1
[INFO] 2019-10-29 10:59:07,447 Throw jobID:[31318] jobCmd:[/mnt/ilustre/centos7users/name/Training/Nextdenovo/test_nextDenovo/01_rundir/01.raw_align/01.db_split.sh.work/db_split0/nextDenovo.sh] in the local_cycle.
[INFO] 2019-10-29 10:59:08,097 db_split done
[INFO] 2019-10-29 10:59:08,101 analysis tasks done
[INFO] 2019-10-29 10:59:08,115 total jobs: 5
[INFO] 2019-10-29 10:59:08,115 Throw jobID:[31325] jobCmd:[/mnt/ilustre/centos7users/name/Training/Nextdenovo/test_nextDenovo/01_rundir/01.raw_align/02.raw_align.sh.work/raw_align0/nextDenovo.sh] in the local_cycle.
[INFO] 2019-10-29 10:59:08,617 Throw jobID:[31330] jobCmd:[/mnt/ilustre/centos7users/name/Training/Nextdenovo/test_nextDenovo/01_rundir/01.raw_align/02.raw_align.sh.work/raw_align1/nextDenovo.sh] in the local_cycle.
[INFO] 2019-10-29 10:59:10,100 Throw jobID:[31378] jobCmd:[/mnt/ilustre/centos7users/name/Training/Nextdenovo/test_nextDenovo/01_rundir/01.raw_align/02.raw_align.sh.work/raw_align2/nextDenovo.sh] in the local_cycle.
[INFO] 2019-10-29 10:59:10,706 Throw jobID:[31384] jobCmd:[/mnt/ilustre/centos7users/name/Training/Nextdenovo/test_nextDenovo/01_rundir/01.raw_align/02.raw_align.sh.work/raw_align3/nextDenovo.sh] in the local_cycle.
[INFO] 2019-10-29 10:59:12,520 Throw jobID:[31434] jobCmd:[/mnt/ilustre/centos7users/name/Training/Nextdenovo/test_nextDenovo/01_rundir/01.raw_align/02.raw_align.sh.work/raw_align4/nextDenovo.sh] in the local_cycle.
[INFO] 2019-10-29 10:59:14,582 raw_align done
[INFO] 2019-10-29 10:59:14,590 analysis tasks done
[INFO] 2019-10-29 10:59:14,599 total jobs: 2
[INFO] 2019-10-29 10:59:14,600 Throw jobID:[31462] jobCmd:[/mnt/ilustre/centos7users/name/Training/Nextdenovo/test_nextDenovo/01_rundir/01.raw_align/03.sort_align.sh.work/sort_align0/nextDenovo.sh] in the local_cycle.
[INFO] 2019-10-29 10:59:15,102 Throw jobID:[31467] jobCmd:[/mnt/ilustre/centos7users/name/Training/Nextdenovo/test_nextDenovo/01_rundir/01.raw_align/03.sort_align.sh.work/sort_align1/nextDenovo.sh] in the local_cycle.
[INFO] 2019-10-29 10:59:16,882 remove temporary result: /mnt/ilustre/centos7users/name/Training/Nextdenovo/test_nextDenovo/01_rundir/01.raw_align/02.raw_align.sh.work/raw_align2/input.seed.002.2bit.2.ovl
[INFO] 2019-10-29 10:59:16,885 remove temporary result: /mnt/ilustre/centos7users/name/Training/Nextdenovo/test_nextDenovo/01_rundir/01.raw_align/02.raw_align.sh.work/raw_align3/input.seed.002.2bit.3.ovl
[INFO] 2019-10-29 10:59:16,889 remove temporary result: /mnt/ilustre/centos7users/name/Training/Nextdenovo/test_nextDenovo/01_rundir/01.raw_align/02.raw_align.sh.work/raw_align4/input.seed.002.2bit.4.ovl
[INFO] 2019-10-29 10:59:16,893 remove temporary result: /mnt/ilustre/centos7users/name/Training/Nextdenovo/test_nextDenovo/01_rundir/01.raw_align/02.raw_align.sh.work/raw_align0/input.seed.001.2bit.0.ovl
[INFO] 2019-10-29 10:59:16,894 remove temporary result: /mnt/ilustre/centos7users/name/Training/Nextdenovo/test_nextDenovo/01_rundir/01.raw_align/02.raw_align.sh.work/raw_align1/input.seed.001.2bit.1.ovl
[INFO] 2019-10-29 10:59:16,895 remove temporary result: /mnt/ilustre/centos7users/name/Training/Nextdenovo/test_nextDenovo/01_rundir/01.raw_align/02.raw_align.sh.work/raw_align2/input.seed.001.2bit.2.ovl
[INFO] 2019-10-29 10:59:16,901 sort_align done
[INFO] 2019-10-29 10:59:16,905 analysis tasks done
[INFO] 2019-10-29 10:59:16,915 total jobs: 2
[INFO] 2019-10-29 10:59:16,916 Throw jobID:[31481] jobCmd:[/mnt/ilustre/centos7users/name/Training/Nextdenovo/test_nextDenovo/01_rundir/02.cns_align/01.get_cns.sh.work/get_cns0/nextDenovo.sh] in the local_cycle.
[INFO] 2019-10-29 10:59:17,417 Throw jobID:[31486] jobCmd:[/mnt/ilustre/centos7users/name/Training/Nextdenovo/test_nextDenovo/01_rundir/02.cns_align/01.get_cns.sh.work/get_cns1/nextDenovo.sh] in the local_cycle.
[INFO] 2019-10-29 10:59:24,685 get_cns done
[INFO] 2019-10-29 10:59:24,685 cns finished, and final corrected reads file:
[INFO] 2019-10-29 10:59:24,685 [35m /mnt/ilustre/centos7users/name/Training/Nextdenovo/test_nextDenovo/./01_rundir/02.cns_align/01.get_cns.sh.work/get_cns*/cns.fasta [0m
[INFO] 2019-10-29 10:59:24,688 analysis tasks done
[INFO] 2019-10-29 10:59:24,697 total jobs: 3
[INFO] 2019-10-29 10:59:24,697 Throw jobID:[31530] jobCmd:[/mnt/ilustre/centos7users/name/Training/Nextdenovo/test_nextDenovo/01_rundir/02.cns_align/02.cns_align.sh.work/cns_align0/nextDenovo.sh] in the local_cycle.
[INFO] 2019-10-29 10:59:25,199 Throw jobID:[31535] jobCmd:[/mnt/ilustre/centos7users/name/Training/Nextdenovo/test_nextDenovo/01_rundir/02.cns_align/02.cns_align.sh.work/cns_align1/nextDenovo.sh] in the local_cycle.
[INFO] 2019-10-29 10:59:26,710 Throw jobID:[31583] jobCmd:[/mnt/ilustre/centos7users/name/Training/Nextdenovo/test_nextDenovo/01_rundir/02.cns_align/02.cns_align.sh.work/cns_align2/nextDenovo.sh] in the local_cycle.
[INFO] 2019-10-29 10:59:28,642 cns_align done
[INFO] 2019-10-29 10:59:28,644 analysis tasks done
[INFO] 2019-10-29 10:59:28,675 total jobs: 11
[INFO] 2019-10-29 10:59:28,676 Throw jobID:[31612] jobCmd:[/mnt/ilustre/centos7users/name/Training/Nextdenovo/test_nextDenovo/01_rundir/03.ctg_graph/01.ctg_graph.sh.work/ctg_graph00/nextDenovo.sh] in the local_cycle.
[INFO] 2019-10-29 10:59:29,178 Throw jobID:[31617] jobCmd:[/mnt/ilustre/centos7users/name/Training/Nextdenovo/test_nextDenovo/01_rundir/03.ctg_graph/01.ctg_graph.sh.work/ctg_graph01/nextDenovo.sh] in the local_cycle.
[INFO] 2019-10-29 10:59:29,844 Throw jobID:[31624] jobCmd:[/mnt/ilustre/centos7users/name/Training/Nextdenovo/test_nextDenovo/01_rundir/03.ctg_graph/01.ctg_graph.sh.work/ctg_graph02/nextDenovo.sh] in the local_cycle.
[INFO] 2019-10-29 10:59:30,346 Throw jobID:[31629] jobCmd:[/mnt/ilustre/centos7users/name/Training/Nextdenovo/test_nextDenovo/01_rundir/03.ctg_graph/01.ctg_graph.sh.work/ctg_graph03/nextDenovo.sh] in the local_cycle.
[INFO] 2019-10-29 10:59:30,904 Throw jobID:[31636] jobCmd:[/mnt/ilustre/centos7users/name/Training/Nextdenovo/test_nextDenovo/01_rundir/03.ctg_graph/01.ctg_graph.sh.work/ctg_graph04/nextDenovo.sh] in the local_cycle.
[INFO] 2019-10-29 10:59:31,409 Throw jobID:[31641] jobCmd:[/mnt/ilustre/centos7users/name/Training/Nextdenovo/test_nextDenovo/01_rundir/03.ctg_graph/01.ctg_graph.sh.work/ctg_graph05/nextDenovo.sh] in the local_cycle.
[INFO] 2019-10-29 10:59:31,970 Throw jobID:[31648] jobCmd:[/mnt/ilustre/centos7users/name/Training/Nextdenovo/test_nextDenovo/01_rundir/03.ctg_graph/01.ctg_graph.sh.work/ctg_graph06/nextDenovo.sh] in the local_cycle.
[INFO] 2019-10-29 10:59:32,475 Throw jobID:[31653] jobCmd:[/mnt/ilustre/centos7users/name/Training/Nextdenovo/test_nextDenovo/01_rundir/03.ctg_graph/01.ctg_graph.sh.work/ctg_graph07/nextDenovo.sh] in the local_cycle.
[INFO] 2019-10-29 10:59:33,029 Throw jobID:[31660] jobCmd:[/mnt/ilustre/centos7users/name/Training/Nextdenovo/test_nextDenovo/01_rundir/03.ctg_graph/01.ctg_graph.sh.work/ctg_graph08/nextDenovo.sh] in the local_cycle.
[INFO] 2019-10-29 10:59:33,540 Throw jobID:[31665] jobCmd:[/mnt/ilustre/centos7users/name/Training/Nextdenovo/test_nextDenovo/01_rundir/03.ctg_graph/01.ctg_graph.sh.work/ctg_graph09/nextDenovo.sh] in the local_cycle.
[INFO] 2019-10-29 10:59:34,089 Throw jobID:[31672] jobCmd:[/mnt/ilustre/centos7users/name/Training/Nextdenovo/test_nextDenovo/01_rundir/03.ctg_graph/01.ctg_graph.sh.work/ctg_graph10/nextDenovo.sh] in the local_cycle.
[INFO] 2019-10-29 10:59:35,162 ctg_graph done
[INFO] 2019-10-29 10:59:35,162 nextDenovo finished
[INFO] 2019-10-29 10:59:35,162 final assembly file:
[INFO] 2019-10-29 10:59:35,162 [35m /mnt/ilustre/centos7users/name/Training/Nextdenovo/test_nextDenovo/./01_rundir/03.ctg_graph/01.ctg_graph.sh.work/ctg_graph*/nextgraph.assembly.contig.fasta [0m
[INFO] 2019-10-29 10:59:35,163 final stat files:
[INFO] 2019-10-29 10:59:35,163 [35m /mnt/ilustre/centos7users/name/Training/Nextdenovo/test_nextDenovo/./01_rundir/03.ctg_graph/01.ctg_graph.sh.work/ctg_graph*/nextDenovo.sh.e [0m

**Comment by moold** [comment]
see #15.
