### ISSUE TITLE
The error of the seed_cutoff

### ISSUE THREAD

**Issue by shehongbing** [Nextomics/NextDenovo#24]
Hi, 
     when I used the seq_stat to analysis my data, but the results equal to 0 bp

*Suggested length cutoff of reads (genome size: 980000000, expected seed depth: 45) to be corrected: 0 bp

**Comment by moold** [comment]
Two possible reasons:
1. Total coverage < 45X, please sequencing more data.
2. Some reads do not have a corrected fasta/fastq format, please check your data format. This is a common issue for NanoPore data.

**Comment by shehongbing** [comment]
Thank you
