### ISSUE TITLE
task = ？

### ISSUE THREAD

**Issue by 25352697** [Nextomics/NextDenovo#25]
What is the relationship between 'correct' and 'assemble'  ?

**Comment by moold** [comment]
NextDenovo use a `correct-then-assemble` strategy, so it will do the self-correction, firstly (corrrect step), and then assemble the corrected reads using string-graph, and output the assembled genome (assemble step). In most situations, you can set `task = 'all'`.

**Comment by 25352697** [comment]
Could I use task = 'correct' firstly, and then I use task = 'assembly'.

**Comment by moold** [comment]
Yes.

**Comment by 25352697** [comment]
Thank U!
