### ISSUE TITLE
NextDenovo assemble has no result file

### ISSUE THREAD

**Issue by ruanyingfei** [Nextomics/NextDenovo#26]
My problem is that my process runs out, but there are no final assembled result,There ais only 01_rundir/02.cns_align/01.get_cns.sh.work/get_cns0/cns.fasta.

my run.cfg is:
[General]
job_type = local
job_prefix = nextDenovo
task = all
rewrite = yes # yes/no
input_type = raw
input_fofn = ./input.fofn
workdir = ./nb_assmble

[correct_option]
read_cuoff = 1k
seed_cutoff = 32k
blocksize = 1g
pa_raw_align = 2
pa_correction = 2
seed_cutfiles = 2
sort_options = -m 1g -t 2 -k 50
minimap2_options = -x ava-pb -t 8
correction_options = -p 15

[assemble_option]
random_round = 20
minimap2_options_cns = -x ava-pb -t 8 -k17 -w17
nextgraph_options = -a 1

The final content of the report file:
[INFO] 2019-11-07 10:18:43,231 remove temporary result: /share/microlab/student/ruanyingfei/biosoft/NextDenovo/test_data/nb_assmble/01.raw_align/02.raw_align.sh.work/raw_align18/input.seed.002.2bit.18.ovl
[INFO] 2019-11-07 10:18:43,352 sort_align done
[INFO] 2019-11-07 10:18:43,387 analysis tasks done
[INFO] 2019-11-07 10:18:43,544 total jobs: 2
[INFO] 2019-11-07 10:18:43,545 Throw jobID:[4798] jobCmd:[/share/microlab/student/ruanyingfei/biosoft/NextDenovo/test_data/nb_assmble/02.cns_align/01.get_cns.sh.work/get_cns0/nextDenovo.sh] in the local_cycle.
[INFO] 2019-11-07 10:18:44,079 Throw jobID:[4821] jobCmd:[/share/microlab/student/ruanyingfei/biosoft/NextDenovo/test_data/nb_assmble/02.cns_align/01.get_cns.sh.work/get_cns1/nextDenovo.sh] in the local_cycle.

Looking forward to your valuable advice, thank you very much!!!

**Comment by moold** [comment]
How about your genome size and input date size?

**Comment by ruanyingfei** [comment]
my genome size is 27M and input data size is 9.1G.

**Comment by moold** [comment]
Could you paste the [seq_stat](https://github.com/Nextomics/NextDenovo/blob/master/doc/UTILITY.md#seq_stat) result to here?

**Comment by moold** [comment]
BTW, do you use the latest version of NextDenovo?

**Comment by ruanyingfei** [comment]
Thank you very much! I've solved this problem, and I didn't get results before because the software I downloaded wasn't the latest version, and there was no nextgraph  in its NextDenovo/bin directory, so there was no final assembly result.Thank you again!
