### ISSUE TITLE
task assemble error

### ISSUE THREAD

**Issue by 25352697** [Nextomics/NextDenovo#27]
Hi,
After correct task,  I run 'assemble task', but I got this error. 

Could you give me a help?

**Traceback (most recent call last):
  File "/home/wangbo/softwares/NextDenovo/nextDenovo", line 518, in <module>
    main(args)
  File "/home/wangbo/softwares/NextDenovo/nextDenovo", line 448, in main
    cns_output = get_cns_output(task.subtasks)
UnboundLocalError: local variable 'task' referenced before assignment**

**Comment by moold** [comment]
you can try to set task=all， and do not change the work directory.

**Comment by 25352697** [comment]
Hi, rewrite = yes or no ?

**Comment by moold** [comment]
rewrite = yes
