### ISSUE TITLE
Running error assembling Pacbio data

### ISSUE THREAD

**Issue by Dichromatism** [Nextomics/NextDenovo#28]
Hello!
I am trying to use NextDenovo these days and found it's okay using Ont data. But when I was trying to assemble Pacbio data some errors appeared and I cannot figure out.
There were Errors in the ./02.cns_align/02.cns_align.sh.work/cns_align*/nextDenovo.sh.e which showed 
`[ERROR] failed to find seq file type or empty file `.
I wrote
```
 [correct_option]
read_cutoff = 1k
seed_cutoff = 1057
blocksize = 3g
pa_correction = 20
seed_cutfiles = 20
sort_options = -m 20g -t 10 -k 20
minimap2_options_raw = -x ava-pb -H -t 8
correction_options = -p 15

[assemble_option]
random_round = 20
minimap2_options_cns = -x ava-pb -H -t 8 -k17 -w17
nextgraph_options = -a 1

```
in my run.cfg when the errors come out.
I need help, thanks!

**Comment by moold** [comment]
I guess the input file of some tasks: `./02.cns_align/02.cns_align.sh.work/cns_align*/nextDenovo.sh`  is empty, and try to increase the value of `-k` in `sort_options = -m 20g -t 10 -k 20`. 20 is too small, recommend `>= 40`.
