### ISSUE TITLE
NextDenovo/bin/seq_dump: cannot execute binary file

### ISSUE THREAD

**Issue by YongZhou2019** [Nextomics/NextDenovo#29]
Hello, I meet a problem when I run nextdenovo. Please give me suggestions about how to fix this. Details are shown as follows. I download this in my labtop, MACpro, 64bit. 
Thanks!

(python2) on-campus-10-138-71-78:**### NextDenovo yongzhou$ nextDenovo test_data/run.cfg** 
[INFO] 2019-11-13 22:25:58,016 start...
[INFO] 2019-11-13 22:25:58,016 logfile: pid933.log.info
[WARNING] 2019-11-13 22:25:58,016 It seems that you are using the default value of "seed_cutoff", it is recommended to use "bin/seq_stat" to calculate this value, because this value will be greatly affected by reads length and sequencing depth, and an inappropriate value can significantly reduce assembly quality.
[WARNING] 2019-11-13 22:25:58,017 Re-write workdir
[INFO] 2019-11-13 22:25:58,017 options: 
[INFO] 2019-11-13 22:25:58,017 {'sort_threads': 2, 'nodelist': '', 'rewrite': 1, 'blocksize': '1g', 'job_prefix': 'nextDenovo', 'job_type': 'local', 'minimap2_options_raw': '-x ava-ont -t 8', 'cns_threads': 15, 'sort_mem': '1g', 'seed_cutoff': '29999', 'input_fofn': '/Users/yongzhou/Softwares/13_NextDenovo/NextDenovo/test_data/./input.fofn', 'read_cutoff': '1k', 'input_type': 'raw', 'sort_options': '-m 1g -t 2 -k 50', 'parallel_jobs': '2', 'cluster_options': '', 'ctg_graphdir': '/Users/yongzhou/Softwares/13_NextDenovo/NextDenovo/test_data/./01_rundir/03.ctg_graph', 'pa_correction': '2', 'workdir': '/Users/yongzhou/Softwares/13_NextDenovo/NextDenovo/test_data/./01_rundir', 'random_round': '10', 'minimap2_threads': (8, 8), 'minimap2_options_cns': '-x ava-ont -t 8 -k17 -w17', 'cns_aligndir': '/Users/yongzhou/Softwares/13_NextDenovo/NextDenovo/test_data/./01_rundir/02.cns_align', 'seed_cutfiles': '2', 'raw_aligndir': '/Users/yongzhou/Softwares/13_NextDenovo/NextDenovo/test_data/./01_rundir/01.raw_align', 'task': 'all', 'deltmp': 1, 'rerun': 3, 'correction_options': '-p 15 -max_lq_length 10000', 'nextgraph_options': '-a 1'}
[INFO] 2019-11-13 22:25:58,017 skip mkdir: /Users/yongzhou/Softwares/13_NextDenovo/NextDenovo/test_data/./01_rundir
[INFO] 2019-11-13 22:25:58,017 skip mkdir: /Users/yongzhou/Softwares/13_NextDenovo/NextDenovo/test_data/./01_rundir/01.raw_align
[INFO] 2019-11-13 22:25:58,017 skip mkdir: /Users/yongzhou/Softwares/13_NextDenovo/NextDenovo/test_data/./01_rundir/02.cns_align
[INFO] 2019-11-13 22:25:58,018 skip mkdir: /Users/yongzhou/Softwares/13_NextDenovo/NextDenovo/test_data/./01_rundir/03.ctg_graph
[INFO] 2019-11-13 22:25:58,019 analysis tasks done
[INFO] 2019-11-13 22:25:58,019 total jobs: 1
[INFO] 2019-11-13 22:25:58,020 Throw jobID:[940] jobCmd:[/Users/yongzhou/Softwares/13_NextDenovo/NextDenovo/test_data/01_rundir/01.raw_align/01.db_split.sh.work/db_split0/nextDenovo.sh] in the local_cycle.
**[ERROR] 2019-11-13 22:25:58,540 db_split failed: please check the following logs:
[ERROR] 2019-11-13 22:25:58,540** /Users/yongzhou/Softwares/13_NextDenovo/NextDenovo/test_data/01_rundir/01.raw_align/01.db_split.sh.work/db_split0/nextDenovo.sh.e
(python2) on-campus-10-138-71-78:NextDenovo yongzhou$ less /Users/yongzhou/Softwares/13_NextDenovo/NextDenovo/test_data/01_rundir/01.raw_align/01.db_split.sh.work/db_split0/nextDenovo.sh.e
(python2) on-campus-10-138-71-78:NextDenovo yongzhou$ 
hostname
+ hostname
cd /Users/yongzhou/Softwares/13_NextDenovo/NextDenovo/test_data/01_rundir/01.raw_align/01.db_split.sh.work/db_split0
+ cd /Users/yongzhou/Softwares/13_NextDenovo/NextDenovo/test_data/01_rundir/01.raw_align/01.db_split.sh.work/db_split0
time /Users/yongzhou/Softwares/13_NextDenovo/NextDenovo/bin/seq_dump -f 1k -s 29999 -b 1g -n 2 -d /Users/yongzhou/Softwares/13_NextDenovo/NextDenovo/test_data/01_rundir/01.raw_align /Users/yongzhou/Softwares/13_NextDenovo/NextDenovo/test_data/input.fofn
+ /Users/yongzhou/Softwares/13_NextDenovo/NextDenovo/bin/seq_dump -f 1k -s 29999 -b 1g -n 2 -d /Users/yongzhou/Softwares/13_NextDenovo/NextDenovo/test_data/01_rundir/01.raw_align /Users/yongzhou/Softwares/13_NextDenovo/NextDenovo/test_data/input.fofn
/Users/yongzhou/Softwares/13_NextDenovo/NextDenovo/test_data/01_rundir/01.raw_align/01.db_split.sh.work/db_split0/nextDenovo.sh: line 5: ### **/Users/yongzhou/Softwares/13_NextDenovo/NextDenovo/bin/seq_dump: cannot execute binary file**

**Comment by moold** [comment]
Currently, NextDenovo does not support MAC system, I will try to release a mac-compatible version in the future.

**Comment by YongZhou2019** [comment]
Got it. Looking forward to the MAC-compatible version. Thanks so much!

Best,
Yong

Hu Jiang <notifications@github.com> 于2019年11月14日周四 上午4:02写道：
