### ISSUE TITLE
How to get genome assembly larger than 3.5G?

### ISSUE THREAD

**Issue by zijiangyang** [Nextomics/NextDenovo#31]
Hi Hu:

Here is part of the log from graph step:
`Min.               22857                    -
Max.             8011581                    -
Ave.              402903                    -
Total         4973432366                12344
[WARNING] 2019-11-19 10:28:10 Unfinished assembly, this is a limited version, currently only supports assembly for genome size < 3500000000 bp, please ask for help.`
May I ask is there ways to get genome assembly larger than 3.5G? 

Thanks!

**Comment by moold** [comment]
I am sorry about that, but according to the NextOmics's  regulation, the current release only supports assembly genome size less than 3.5g, which covers most of genomes need to be assemble. But if you want to assemble a larger genome, please contant [NextOmics](https://www.nextomics.cn/en/).
