### ISSUE TITLE
Cann't get the cns.fasta

### ISSUE THREAD

**Issue by shehongbing** [Nextomics/NextDenovo#32]
HI,
    there are 20 get_cns**  directory  but only in get_cns01 directory that I can not get the cns.fasta.  and the nextDenovo.sh.e shown is following:

/ifs1/User/shehongbing/zhuang/next/n02/01_rundir_yy/02.cns_align/01.get_cns.sh.work/get_cns01/nextDenovo.sh: 行 5: 448178 段错误               python /ifs1/User/shehongbing/soft/NextDenov    o/lib/nextcorrect.py -f /ifs1/User/shehongbing/zhuang/next/n02/01_rundir_yy/02.cns_align//01.get_cns.input.idxs -i /ifs1/User/shehongbing/zhuang/next/n02/01_rundir_yy/01.raw_align/03.sort    _align.sh.work/sort_align01/input.seed.002.sorted.ovl -p 7 -max_lq_length 10000 -o cns.fasta

but I compare  the nextDenove.sh with others in get_cns03 directory, actually, its no mistakes at all.

**Comment by moold** [comment]
What is your NextDenovo version?

**Comment by shehongbing** [comment]
v2.1-beta.0.       others could word correctly except get_cns01

**Comment by moold** [comment]
It seems some errors in this file, `/ifs1/User/shehongbing/zhuang/next/n02/01_rundir_yy/01.raw_align/03.sort _align.sh.work/sort_align01/input.seed.002.sorted.ovl `, you can try to rerun this task:`/ifs1/User/shehongbing/zhuang/next/n02/01_rundir_yy/01.raw_align/03.sort _align.sh.work/sort_align01/*sh`, but pls rerun its corresponding minimap2 tasks first to prepare its input.

**Comment by shehongbing** [comment]
Thank you,  I’ll try it

**Comment by shehongbing** [comment]
Hi, 
it dose work correctly. thank you Dr. Hu.  And I have another question. raw data and corrected data (by canu), which is better for NextDenovo

**Comment by moold** [comment]
For another question,  you should open a new issue.
