### ISSUE TITLE
Assemble the genome with corrected fasta using NextDenovo2.1

### ISSUE THREAD

**Issue by jiahaow123456** [Nextomics/NextDenovo#35]
HI,
    I am trying to assemble the genome with corrected fasta using NextDenovo2.1. 
    I have set 'task = assemble', 'input_type = corrected' and 'input.fofn' containing corrected fasta files but something is wrong. 
    The input fasta files were generated by NextDenovo1 and have been compressed and moved to another place. How could I just running the assemble step with the corrected data?
    Thank you!

**Comment by moold** [comment]
If the corrected data were generated by NextDenovo, just set `task=all`, and run the same main command again, please keep the primary directory structure. If  the primary directory structure has been changed or  the corrected data were generated by other tools, currently, NextDenovo will not work. I will fixed it in the future release.

**Comment by jiahaow123456** [comment]
OK，thank you~
