### ISSUE TITLE
there is not enough disk space

### ISSUE THREAD

**Issue by shehongbing** [Nextomics/NextDenovo#37]
HI, 
     I have 80G raw data and my disk space is 2T. Actually,  it not enough disk space for me, so what should I do?

**Comment by moold** [comment]
Do you use set this option: `deltmp = yes`?  In theory, NextDenovo should not use 2T disk space for a normal genome with 80G raw data. But if you have set `deltmp = yes`, you can try to set `minimap2_options_raw = -x ava-ont --minlen 1000`.

**Comment by shehongbing** [comment]
Yes,  I set the option deltmp = yes. It’s because there are about 270 raw_align files  in /01.raw_align/02.raw_align.sh.work and  each raw_align with 20G

**Comment by moold** [comment]
It means your genome is a high repetitive genome, so pls try to use `minimap2_options_raw = -x ava-ont --minlen 1000`  to filter short repeat hits.

**Comment by shehongbing** [comment]
Hi, I try it. actually, it still need to about 6T disk space

**Comment by moold** [comment]
If you still want to reduce the disk space requirements, just increase `--minlen`.

**Comment by shehongbing** [comment]
Thank you
