### ISSUE TITLE
ovl_sort.c:688: main: Assertion `opts.max_mem > 100000000' failed

### ISSUE THREAD

**Issue by wook2014** [Nextomics/NextDenovo#38]
I am trying to use nextdenovo to assembly the data of a fungi. but the following problem occurs. what is it about and how could I solve it ?
ovl_sort: ovl_sort.c:688: main: Assertion `opts.max_mem > 100000000' failed.
Command terminated by signal 6

**Comment by moold** [comment]
see #5
