### ISSUE TITLE
how can I reduce the number of process and storage at raw align step？

### ISSUE THREAD

**Issue by zhenzhenS** [Nextomics/NextDenovo#39]
Hi ,

I want to use the nextdenovo to assembly PB reads. And I run it by SGE. I notice that the submissions of step2 raw reads align require lots of resources and processes. That led to those tasks that can't be run. So the question is how can I reduce the number of processes and storage at raw align step？ Hope your help. Thanks a lot.

**Comment by moold** [comment]
See FAQ iii & iv
