### ISSUE TITLE
NextDenovo is unfinished

### ISSUE THREAD

**Issue by dzaccook** [Nextomics/NextDenovo#4]
Hi,
My NextDenovo has run five days in cns_align step, there are 49 jobs and 15 have finished, I can see the jobs using "top" and the status are "S", but the log files has not been updated  too long time. 
can you give me some help?
Thank you.

**Comment by moold** [comment]
Hi, are there any core.* files in the directories of unfinished jobs?

**Comment by moold** [comment]
BTW, Could you check the updated time of cns.fasta files?

**Comment by dzaccook** [comment]
1. are there any core.* files in the directories of unfinished jobs?   NO.
2. the updated time of cns.fasta files is five days ago.

**Comment by moold** [comment]
Maybe I need to debug and find the error details, so
1. Is there any way to let me login your computer and debug it? you can email the login details to me.
or  you can send me all the input file of one unfinished job.
2. If the size of cns.fasta file in unfinished directories is similar with the size of finished jobs, you can ignore unfinished seqs and it usually make no big difference for assembly with a little less data.

**Comment by dzaccook** [comment]
Thank you for your reply. Sorry, because of the system of management, login the computer need  to apply. I check the size of cns.fasta file and there are similar.

**Comment by moold** [comment]
Ok.
