### ISSUE TITLE
Add GFA in output

### ISSUE THREAD

**Issue by xuzhougeng** [Nextomics/NextDenovo#40]
Many assembler output [GFA](http://gfa-spec.github.io/GFA-spec/), such as Canu, miniasm.  

This file can be visualized in Bandage for check the assembly.

Could you add the this format output in future development?

**Comment by moold** [comment]
see [nextgraph option](https://github.com/Nextomics/NextDenovo/blob/master/doc/UTILITY.md/#nextgraph), you will find -a option can be used to define output format.

**Comment by kim-fehl** [comment]
The link above doesn't work, this does: https://nextdenovo.readthedocs.io/en/latest/UTILITY.html#nextgraph
