### ISSUE TITLE
analysis tasks done but the following pipeline died (KeyError: '009')

### ISSUE THREAD

**Issue by DengHAU** [Nextomics/NextDenovo#42]
Hi, Dr,Hu
Recently, I use nextDenovo to assembly a plant genome. It is extremely fast doing reads alignment. But when this step is done, the pipeline died and throwed  the follwing error:
[INFO] 2019-12-17 10:15:14,462 analysis tasks done
[INFO] 2019-12-17 10:15:14,463 skip step: db_split
[INFO] 2019-12-17 10:15:14,485 analysis tasks done
[INFO] 2019-12-17 10:15:14,487 skip step: raw_align
[INFO] 2019-12-17 10:15:14,554 analysis tasks done
Traceback (most recent call last):
  File "/home/software/bin/nextDenovo", line 518, in <module>
    main(args)
  File "/home/software/bin/nextDenovo", line 410, in main
    pre_sort_align_input(sort_align_input, task.run.unfinished_tasks)
  File "/home/software/bin/nextDenovo", line 153, in pre_sort_align_input
    for input_file in sort_align_input[seed_idx]:
KeyError: '009'

I also rerun the pipeline, the same error came again. Any suggestion?

Thanks.

**Comment by moold** [comment]
Did you delete some intermediate result files? Did you successfully run the test data?

**Comment by DengHAU** [comment]
Thanks for your kindly reploy,

I don't run test data. When nextDenovo first releaed without assembly model，I use nextdenovo to do reads cerrection, and it works good. Now you release the assembly part, I download the whole package and want to use nextgraph to do contiger, and I got this error. I don't delete some intermediate result files manualy,but I chose `deltmp = yes` in run.ctg

**Comment by moold** [comment]
The currently release is not compatible with the old version. So maybe you need rerun all pipeline.

**Comment by DengHAU** [comment]
Thanks a lot!
I will try again.

**Comment by DengHAU** [comment]
It's the compatibility problem. I deleted the reads carrection results genereted by the first released package and rerun the pipeline. Now it's move to CNS step. Thanks a lot.
