### ISSUE TITLE
how to run on LSF system?

### ISSUE THREAD

**Issue by huangyixian123** [Nextomics/NextDenovo#43]
Hi! I want to use NextDenovo on my LSF system, but when I set  "lsf" on " job_type" of "run.cfg", the system get the following error: drmaa.errors.InternalException: code 1: Please set the environment variable SGE_ROOT. 
So my questions are:
1. Does NextDenovo work on lsf system？how to set run.cfg (especially "cluster_options" )?
2. how to set "SGE_ROOT" or somethings like "LSF_ROOT" of drmaa-python in LSF system? Does drmaa-python work on lsf system? And I found a another tool named lsf-drmaa? Does lsf-drmaa work on NextDenovo? what is the the relationship between drmaa-python and lsf-drmaa？

**Comment by moold** [comment]
Q1. see [ParallelTask](https://github.com/moold/ParallelTask) for help.
Q2. I have no idea about this, because they are third-party packages, only used by NextDenovo, maybe you can ask for help in the issue page of `lsf-drmaa` or `drmaa-python`.
