### ISSUE TITLE
assemble result 

### ISSUE THREAD

**Issue by shehongbing** [Nextomics/NextDenovo#44]
when I used raw Nanopore data, the assemble.fa N50 is about 39 Mb, but the alignment is not good in comparison to published genome. however, when I used collected data (corrected by canu), the assemble.fa N50 is about 2 Mb, and with the good alignment in comparison to the polished genome. So I do not know why.  it suggested that should I used the corrected data rather than raw data?    and the two methods with the huge different in N50

**Comment by moold** [comment]
What is the NextDenovo version you used? and how about the genome size, heterozygous rate, and repeat content? I do not suggested use corrected data, because NextDenovo will correct the raw data and filter some low quality or unuseful seeds. BTW, Could you provide the co-line pictures?

**Comment by moold** [comment]
How about the assembly result using canu?

**Comment by shehongbing** [comment]
1. I used the  NextDenovo v2.1-beta.0
2. The genome size I used is about 980 Mb, heterozygous rate is 0.119%

The figure 1 is raw data, figure 2 is corrected data


Figure1 



Figure 2

**Comment by moold** [comment]
I can not see the figures, if you have problem to upload the figures to github, you can send the figures to my email: huj_at_grandomics.com. BTW, could you provide the configure file and the assembly log (the last step log)?

**Comment by shehongbing** [comment]
Hi, 
Dr. Hu

I sent it to you few minutes ago

**Comment by moold** [comment]
I find your seed_cutoff is very short? How many data you used to do the assembly?

**Comment by shehongbing** [comment]
My raw data is about 40 G. 


[Read length stat]
Types            Count (#) Length (bp)
N10                  47170   73938
N20                 110964   59801
N30                 187662   50562
N40                 277752   43236
N50                 382891   37077
N60                 505656   31670
N70                 650141   26749
N80                 823069   22065
N90                1037363   17256

Types               Count (#)           Bases (bp)  Depth (X)
Raw                   1503768          42060488746      42.92
Filtered                    0                    0       0.00
Clean                 1503768          42060488746      42.92

*Suggested length cutoff of reads (genome size: 980000000, expected seed depth: 40) to be corrected: 15170 bp

**Comment by moold** [comment]
Your data is not enough for assembly using the currently version of NextDenovo with default options, because all default options are optimize with 60-100x nanopore data. So it will produce an unexpected assembly result. But if you still want to use NextDenovo to do the assembly, you can try to use the option `correction_options = -b` and change `-k 30` in `sort_options` and than rerun all pipeline, while I can not guarantee you can get a good result.  You also can try to other assemblers. I will release a set of preset parameters for assembly with low-depth data in the future.

**Comment by shehongbing** [comment]
Thank you
