### ISSUE TITLE
nextgraph: asg.c:1270: update_graph: Assertion `mode == 10' failed.

### ISSUE THREAD

**Issue by huangyixian123** [Nextomics/NextDenovo#47]
Hi! I get the following error in "01_rundir/03.ctg_graph/01.ctg_graph.sh.work/ctg_graph00/nextDenovo.sh.e": 
"nextgraph: asg.c:1270: update_graph: Assertion `mode == 10' failed.
01_rundir/03.ctg_graph/01.ctg_graph.sh.work/ctg_graph01/nextDenovo.sh: line 5: 208229 Aborted                 (core dumped) /apps/NextDenovo/bin/nextgraph -a 0 -n 45 -f 01_rundir/03.ctg_graph/01.ctg_graph.input.seqs 01_rundir/03.ctg_graph/01.ctg_graph.input.ovls". What should I do to solve it? Thanks!

**Comment by moold** [comment]
Hi，could you check whether any input ovl file is empty?

**Comment by huangyixian123** [comment]
There is not empty "cns.filt.dovt.ovl" in "/02.cns_align/02.cns_align.sh.work/cns_align*".

**Comment by moold** [comment]
Hi, maybe you can  try to decompress the ovl files using [bin/ovl_cvt](https://github.com/Nextomics/NextDenovo/blob/master/doc/UTILITY.md#ovl_cvt) to see which file induced this problem? and re-generate this ovl file again.
