### ISSUE TITLE
sort_overlap error

### ISSUE THREAD

**Issue by northbio** [Nextomics/NextDenovo#5]
/home/soft/NextDenovo/bin/sort_overlap -m 100M -t 3 -k 50 -i /home/soft/NextDenovo/test_data/./01_rundir/01.raw_align/.input.seed.001.idx -o input.seed.001.sorted.ovl input.fofn
sort_overlap: sort_overlap.c:1023: main: Assertion `opts.max_mem > 2.2 * 100000000' failed.
Aborted (core dumped)

This error happens not matter how I change -m and -t ......

**Comment by northbio** [comment]
my system is CentOS Linux release 7.2.1511 (Core)

**Comment by northbio** [comment]
my command is :   
nextDenovo test_data/run.cfg -l log.txt

And 
more test_data/run.cfg
[General]
job_type = local
job_prefix = nextDenovo
task = all
rewrite = yes # yes/no
input_type = raw
input_fofn = ./input.fofn
workdir = ./01_rundir

[correct_option]
read_cuoff = 1k
seed_cutoff = 32k
blocksize = 1g
pa_raw_align = 2
pa_correction = 2
seed_cutfiles = 2
sort_options = -m 1g -t 10 -k 50
minimap2_options = -x ava-ont -t 15
correction_options = -p 15

**Comment by moold** [comment]
I find in you config file, sort_options  = -m 1g -t 10 -k 50, but in your command sort_options = -m 100M -t 3 -k 50 ? Please check this first.

**Comment by northbio** [comment]
I tried both -m 1g and -m 100M, but both gave the same error infomation.....

**Comment by moold** [comment]
Please insure each thread has a buffer size > 100M,  and -m is to set total buffer size for all threads (-t), so just increase -m, and for sort_options = -m 1g -t 10 -k 50, just reset -m 1g to -m 1.1g is ok.

**Comment by moold** [comment]
I will close this issue, but if you still have this problem, feel free to reopen it.
