### ISSUE TITLE
problem:The data from canu's correctedReads had no results with the nextdenovo software.

### ISSUE THREAD

**Issue by clover163** [Nextomics/NextDenovo#50]
Hi, I have a problem about the nextdenovo assemble task. when I used the data from canu's correctedReads to assemble, I couldn,t get any results . 
run.cfg:
[General]
job_type = sge
job_prefix = ***
task =assemble # 'all', 'correct', 'assemble'
rewrite = yes # yes/no
deltmp = yes
rerun = 3
parallel_jobs = 200
input_type = corrected
......
[assemble_option]
random_round = 100
minimap2_options_cns = -x ava-pb -t 8 -k17 -w17
nextgraph_options = -a 1

Please give me some advises to solve this problem.
Thanks a lot !!!

**Comment by moold** [comment]
Could you provide the unfinished subtask log and NextDenovo version? 
BTW, the assembly module of NextDenovo with default parameters is primary designed for reads corrected by NextCorrect (the first module of NextDenovo), and I do not test it with reads corrected with Canu, so the result is uncertain, pls check the quality after getting the assembly result.

**Comment by clover163** [comment]
All jobs have been done, but the assembly fasta is empty .Maybe I should try other parameters?
 NextDenovo version:NextDenovo-v2.2-beta.0

**Comment by moold** [comment]
Hi, could you try to rename the corrected reads ID with integer (`int`), and rerun all pipeline?

**Comment by clover163** [comment]
enmm, means I should rename  reands ID ,and then , run pipeline with "task = all“ ，or just rerun with "task =assemble" ?

**Comment by moold** [comment]
`task =assemble`

**Comment by clover163** [comment]
Hi,  NextDenovo version is NextDenovo-v2.2-beta.0, how can I solve the problem:
 Unfinished assembly, this is a limited version, currently only supports assembly for genome size < 3500000000 bp, please ask for help.

**Comment by moold** [comment]
See #31 and #52
