### ISSUE TITLE
Question about -b, --blacklist

### ISSUE THREAD

**Issue by iggyB** [Nextomics/NextDenovo#53]
Hej!

Could you please elaborate a bit more on the filtering happening during correction? What are criteria for reads to be blacklisted?
You mentioned "-b" in issues #52, #49 and #44, but would be interesting to know the reason for default filtering.

Cheers,
Iggy

**Comment by moold** [comment]
I  have explained it in #52, for more detals, pls read our paper if I plan to publish it.

**Comment by iggyB** [comment]
Thanks for quick response! You mention in #52 that:
> by setting -b , NextCorrect will ignore some reads that are not useful for NextGraph, while these reads may be useful for other assembly tools. 

My question was why **some reads are not useful and ignored**? 

Good luck with the future paper!
