### ISSUE TITLE
Can not get_cns

### ISSUE THREAD

**Issue by shehongbing** [Nextomics/NextDenovo#54]
HI,

During the get_cns step, it spend a few days but can not get the cns.fasta. And I run it again but it also can not get the cns.fasta. So I run the script nextDenovo.sh, and there is some errors:

hostname
+ hostname
mu01
cd /data/pub/shehb/ONT/nextdenovo/raw_xx_change/raw_n01_newparameter/02.cns_align/01.get_cns.sh.work/get_cns00
+ cd /data/pub/shehb/ONT/nextdenovo/raw_xx_change/raw_n01_newparameter/02.cns_align/01.get_cns.sh.work/get_cns00
time python /data/pub/shehb/soft/NextDenovo/lib/nextcorrect.py -f /data/pub/shehb/ONT/nextdenovo/raw_xx_change/raw_n01_newparameter/02.cns_align//01.get_cns.input.idxs -i /data/pub/shehb/ONT/nextdenovo/raw_xx_change/raw_n01_newparameter/01.raw_align/03.sort_align.sh.work/sort_align00/input.seed.017.sorted.ovl -p 15 -b -max_lq_length 10000 -o cns.fasta;
+ python /data/pub/shehb/soft/NextDenovo/lib/nextcorrect.py -f /data/pub/shehb/ONT/nextdenovo/raw_xx_change/raw_n01_newparameter/02.cns_align//01.get_cns.input.idxs -i /data/pub/shehb/ONT/nextdenovo/raw_xx_change/raw_n01_newparameter/01.raw_align/03.sort_align.sh.work/sort_align00/input.seed.017.sorted.ovl -p 15 -b -max_lq_length 10000 -o cns.fasta
[INFO] 2020-02-21 10:22:33,976 Corrected step options:
[INFO] 2020-02-21 10:22:33,977 Namespace(blacklist=False, dbuf=False, fast=False, idxs='/data/pub/shehb/ONT/nextdenovo/raw_xx_change/raw_n01_newparameter/02.cns_align//01.get_cns.input.idxs', max_cov_aln=130, max_lq_length=10000, min_cov_base=4, min_cov_seed=10, min_error_corrected_ratio=0.8, min_len_aln=500, min_len_seed=10000, out='cns.fasta', ovl='/data/pub/shehb/ONT/nextdenovo/raw_xx_change/raw_n01_newparameter/01.raw_align/03.sort_align.sh.work/sort_align00/input.seed.017.sorted.ovl', process=15, split=False)
Traceback (most recent call last):
  File "/data/pub/shehb/soft/NextDenovo/lib/nextcorrect.py", line 304, in <module>
    main(args)
  File "/data/pub/shehb/soft/NextDenovo/lib/nextcorrect.py", line 224, in main
    pool = Pool(args.process, initializer=start)
  File "/usr/lib64/python2.7/multiprocessing/__init__.py", line 232, in Pool
    return Pool(processes, initializer, initargs, maxtasksperchild)
  File "/usr/lib64/python2.7/multiprocessing/pool.py", line 138, in __init__
    self._setup_queues()
  File "/usr/lib64/python2.7/multiprocessing/pool.py", line 233, in _setup_queues
    self._inqueue = SimpleQueue()
  File "/usr/lib64/python2.7/multiprocessing/queues.py", line 352, in __init__
    self._rlock = Lock()
  File "/usr/lib64/python2.7/multiprocessing/synchronize.py", line 147, in __init__
    SemLock.__init__(self, SEMAPHORE, 1, 1)
  File "/usr/lib64/python2.7/multiprocessing/synchronize.py", line 75, in __init__
    sl = self._semlock = _multiprocessing.SemLock(kind, value, maxvalue)
OSError: [Errno 13] Permission denied

could you please give me some advices 
THX

**Comment by moold** [comment]
It is a system configuration problem, see [here](https://stackoverflow.com/questions/2009278/python-multiprocessing-permission-denied) and ask your system administrator for help.

**Comment by shehongbing** [comment]
Thank you
