### ISSUE TITLE
the problem of software running in v2.2-beta.0 version 

### ISSUE THREAD

**Issue by lbbobo** [Nextomics/NextDenovo#55]
When I ran the test data with nextdenovo v2.2-beta.0 installed, I had a problem！！

Program running parameters：
The parameters in the run.cfg file of  test data are used without modification.

I found that when I ran the following command, the program did not compute (CPU was not used).

minimap2-nd --step 1 -I 3G -x ava-ont -t 8 ./input.seed.001.2bit ./input.seed.001.2bit -o input.seed.001.2bit.1.ovl

**Comment by moold** [comment]
What is your system and how about your system memory? Have you checked uisng `top -p MINIMAP2_ND_SUBTASK_PID`?

**Comment by lbbobo** [comment]
That's 2,019 Gb of  system memory.

the minimap2_nd showed

PID      PR  NI  VIRT  RES  SHR S %CPU %MEM    TIME+  COMMAND
10009     20   0 1346m 1.2g  820 S  0.0  0.1   0:02.09 /vol1/agis/wanfa

**Comment by moold** [comment]
What is your system version and gcc version? The memory is enough.

**Comment by lbbobo** [comment]
system version:
cLSB Version:    :base-4.0-amd64:base-4.0-noarch:core-4.0-amd64:core-4.0-noarch:graphics-4.0-amd64:graphics-4.0-noarch:printing-4.0-amd64:printing-4.0-noarch
Distributor ID: CentOS
Description:    CentOS release 6.5 (Final)
Release:        6.5
Codename:       Final

gcc version:
gcc version 5.4.0 (GCC)

**Comment by DengHAU** [comment]
This problem has also been encountered in my system. In another linux system(CentOS Linux release 7.6.1810 (Core)，gcc 5.4.0), it works well.  Has it been solved?

**Comment by DengHAU** [comment]
Probably the glibc version problem. Using `export LD_PRELOAD=/to/your/path/libc-2.14.so` when you runing can works. Good luck!
