### ISSUE TITLE
NextDenovo on SLURM

### ISSUE THREAD

**Issue by Clement-BIRBES** [Nextomics/NextDenovo#58]
Hi,
I tried to run NextDenovo on slurm, using the option i saw in other issues :
cluster_options = -p workq --cpu-per-taks={cpu} --mem-per-taks {vf}
I also tried to change to -c or -–cpus-per-task={cpu} -–mem-per-cpu={vf}. But run always fail at the same point :

`drmaa.errors.InvalidAttributeValueException: code 14: Invalid native specification: -p workq -c 1 --mem 1G (Unsupported option: -c)`

cpu option is always wrong whatever i try, do you have a solution for that ? (when i'm reserving ressources on this cluster i use -c X and it work perfectly)

**Comment by moold** [comment]
Hi, see FAQ i or [here](https://github.com/moold/ParallelTask)

**Comment by moold** [comment]
Try the latest version, which does not require drmaa.
