### ISSUE TITLE
Reducing RAM usage on a desktop

### ISSUE THREAD

**Issue by nadegeguiglielmoni** [Nextomics/NextDenovo#61]
Hello,

Thank you for this tool. I am trying to run it on a machine with 128 GB RAM and using 14 threads. I have tried to play with some parameters to reduce RAM usage, but everytime my RAM gets saturated. Could you recommend an appropriate set of parameters to avoid going above ~115 GB in RAM usage?

**Comment by moold** [comment]
Hi, could you paste your config file to here?

**Comment by nadegeguiglielmoni** [comment]
I suppose you mean run.cfg ?

[General]
job_type = local
job_prefix = nextDenovo
task = all # 'all', 'correct', 'assemble'
rewrite = yes # yes/no
deltmp = yes
rerun = 3
parallel_jobs = 14
input_type = raw
input_fofn = input.fofn
workdir = 01_rundir

[correct_option]
read_cutoff = 1k
seed_cutoff = 29999
blocksize = 2g
pa_correction = 20
seed_cutfiles = 20
sort_options = -m 20g -t 14 -k 40
minimap2_options_raw = -x ava-ont -t 14
correction_options = -p 15

[assemble_option]
random_round = 20
minimap2_options_cns = -x ava-ont -t 14 -k17 -w17
nextgraph_options = -a 1

**Comment by moold** [comment]
yes, and try the following cfg:
```
[General]
job_type = local
job_prefix = nextDenovo
task = all # 'all', 'correct', 'assemble'
rewrite = yes # yes/no
deltmp = yes
rerun = 3
parallel_jobs = 1
input_type = raw
input_fofn = input.fofn
workdir = 01_rundir

[correct_option]
read_cutoff = 1k
seed_cutoff = 29999
blocksize = 2g
pa_correction = 1
seed_cutfiles = 3
sort_options = -m 50g -t 14 -k 50
minimap2_options_raw = -x ava-ont -t 14
correction_options = -p 10

[assemble_option]
random_round = 20
minimap2_options_cns = -x ava-ont -t 14 -k17 -w17
nextgraph_options = -a 1
```
