### ISSUE TITLE
GLIBC2.14 not found

### ISSUE THREAD

**Issue by YL1004** [Nextomics/NextDenovo#62]
Hello,i am really want to use this software to generate the genome，but it always warn glibc 2.14 not found，i am not the administrator,i can not add the glibc 2.14.Can you tell me what should i do to solve this problem. Thank you

**Comment by moold** [comment]
Hi, what is your system and gcc version?

**Comment by YL1004** [comment]
Hi,its detail is gcc version 4.4.6 20120305 (Red Hat 4.4.6-4) (GCC)

**Comment by YL1004** [comment]
Hi,its detail is&nbsp;gcc version 4.4.6 20120305 (Red Hat 4.4.6-4) (GCC)


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Hu Jiang"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月18日(星期六) 下午2:33
收件人:&nbsp;"Nextomics/NextDenovo"<NextDenovo@noreply.github.com&gt;;
抄送:&nbsp;"我家Misssi"<3152680050@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [Nextomics/NextDenovo] GLIBC2.14 not found (#62)





 
Hi, what is your system and gcc version?

**Comment by moold** [comment]
Could you try to update your gcc version to 4.8.5 or higher?

**Comment by YL1004** [comment]
No,it does not work when i uddate the gcc to 7.+

**Comment by moold** [comment]
Hi, Could you try to [this version](https://github.com/Nextomics/NextDenovo/files/4501854/NextDenovo-Pro-dev.zip), which is the lastest version we are working on and includes some minor changes, any questions are welcome.

**Comment by YL1004** [comment]
Hi，it works,but the false is
Traceback (most recent call last):
&nbsp; File "/next/NextDenovo-Pro-dev/lib/nextcorrect.py", line 310, in <module&gt;
&nbsp; &nbsp; main(args)
&nbsp; File "/next/NextDenovo-Pro-dev/lib/nextcorrect.py", line 228, in main
&nbsp; &nbsp; worker, read_seq_data(args, corrected_seeds), chunksize=1):
&nbsp; File "/home/anaconda3/envs/py27/lib/python2.7/multiprocessing/pool.py", line 673, in next
&nbsp; &nbsp; raise value
UnicodeDecodeError: 'utf8' codec can't decode byte 0xc8 in position 0: invalid continuation byte







------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Hu Jiang"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月20日(星期一) 下午3:37
收件人:&nbsp;"Nextomics/NextDenovo"<NextDenovo@noreply.github.com&gt;;
抄送:&nbsp;"我家Misssi"<3152680050@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [Nextomics/NextDenovo] GLIBC2.14 not found (#62)





 
Hi, Could you try to this version, which is the lastest version we are working on and includes some minor changes, any questions are welcome.

**Comment by moold** [comment]
What is your python version? I cannot reproduce this error.

**Comment by YL1004** [comment]
python version is 2.7.17

**Comment by moold** [comment]
I have tested with python2.7 and python3, it finished without any errors. Could you rerun it with test_data?

**Comment by YL1004** [comment]
ok，i will try it at once

**Comment by YL1004** [comment]
File "/home/wanglei/data/jzw/yl/next/NextDenovo-Pro-dev/lib/ctg_cns.py", line 228, in <module>
    main(args)
  File "/home/wanglei/data/jzw/yl/next/NextDenovo-Pro-dev/lib/ctg_cns.py", line 183, in main
    pool = Pool(args.process, initializer=start)
  File "/home/wanglei/anaconda3/lib/python3.7/multiprocessing/context.py", line 119, in Pool
    context=self.get_context())
  File "/home/wanglei/anaconda3/lib/python3.7/multiprocessing/pool.py", line 176, in __init__
    self._repopulate_pool()
  File "/home/wanglei/anaconda3/lib/python3.7/multiprocessing/pool.py", line 231, in _repopulate_pool
    for i in range(self._processes - len(self._pool)):
TypeError: 'float' object cannot be interpreted as an integer

**Comment by YL1004** [comment]
this python version is 3.7.3

**Comment by moold** [comment]
Du you use the default config file? or paste your config file to here.

**Comment by YL1004** [comment]
thank you ，i try python 2.7 and use the test data ，it finish with out err

**Comment by YL1004** [comment]
hi，when i use my data it occur the same err
my config file is
[General]
job_type = local
job_prefix = nextDenovo
task = all # 'all', 'correct', 'assemble'
rewrite = yes # yes/no
deltmp = yes
rerun = 3
parallel_jobs = 3
input_type = raw
input_fofn = /home/wanglei/data/jzw/yl/next/NextDenovo-Pro-dev/test_data/input.fofn
workdir = /home/wanglei/data/jzw/yl/next/NextDenovo-Pro-dev/test_data/01_rundir

[correct_option]
read_cutoff = 1k
seed_cutoff = 4k
blocksize = 3g
pa_correction = 10
seed_cutfiles = 10
sort_options = -m 2g -t 2 -k 50
minimap2_options_raw = -x ava-ont -t 3
correction_options = -p 15

[assemble_option]
minimap2_options_cns = -x ava-ont -t 8 -k17 -w17
nextgraph_options = -a 1

**Comment by moold** [comment]
you can try to use 
[ctg_cns.zip](https://github.com/Nextomics/NextDenovo/files/4514510/ctg_cns.zip) to replace the same file in the lib directory, and continue to run the unfinished tasks.

**Comment by YL1004** [comment]
it does not work，Thank you for your patient guidance。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Hu Jiang"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月22日(星期三) 下午3:45
收件人:&nbsp;"Nextomics/NextDenovo"<NextDenovo@noreply.github.com&gt;;
抄送:&nbsp;"我家Misssi"<3152680050@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [Nextomics/NextDenovo] GLIBC2.14 not found (#62)





 
you can try to use
 ctg_cns.zip to replace the same file in the lib directory, and continue to run the unfinished tasks.

**Comment by zhk2017** [comment]
I also encountered the same problem, solved in the following way:
step1: download [this version](https://github.com/Nextomics/NextDenovo/files/4501854/NextDenovo-Pro-dev.zip) ,and unzip it;
step2: download nextdenovo from the github(wget https://github.com/Nextomics/NextDenovo/releases/download/v2.2-beta.0/NextDenovo.tgz), and tar -xzvf 
step3: cd step2 installed nextdenovo path, and repalce bin directory with step1's Pro version bin; also replace ctg_cns.so and ovlseq.so with NextDenovo-Pro-dev's ctg_cns.so and ovlseq.so.

At last, use step2 NextDenovo will be ok.

Haikuan
