### ISSUE TITLE
sort_align failed

### ISSUE THREAD

**Issue by ucassee** [Nextomics/NextDenovo#64]
Dear developer, I meet the following error:
2020-05-07 00:48:53,087 sort_align failed: please check the following logs:
[ERROR] 2020-05-07 00:48:53,087 01_rundir/01.raw_align/03.sort_align.sh.work/sort_align00/nextDenovo.sh.e
[ERROR] 2020-05-07 00:48:53,087 2.hagfish/01_rundir/01.raw_align/03.sort_align.sh.work/sort_align01/nextDenovo.sh.e

/software/nextdenovo/NextDenovo/bin/ovl_sort -m 1g -t 20 -k 50 -i ./01_rundir/01.raw_align/.input.seed.001.idx -o input.seed.001.sorted.ovl input.fofn
ovl_sort: ovl_sort.c:688: main: Assertion `opts.max_mem > 100000000' failed.

It seems I didn't call  enough mem. How should I debug this error?
Thanks in advance.

**Comment by moold** [comment]
see #5
