### ISSUE TITLE
Failed in regional assembly by NextDenovo.

### ISSUE THREAD

**Issue by biozhangzhou** [Nextomics/NextDenovo#67]
I did some regional assembly by nextdenovo, some successd but most failed.Then I have two question below.
First： Can i use NextDenovo to do regional(less then 1mb) assembly ?  
Second:  Which paras should i change for reginal assembly ?
Thank you.

**Comment by moold** [comment]
In theory, it should work. so I need more details to figure out, such region size, data size, data type, date length, config file, log file, error files...

**Comment by biozhangzhou** [comment]
The region is about 500kb with ~100x ONT raw reads with totally size ~80Mb, it can running normally without any bug output, but it will running >4hours and seems will not be stop in minimal-nd step.

**Comment by moold** [comment]
I have no idea for this, because there is no error info, If you are using the old version, pls update to the latest version, otherwise just wait for minimal-nd finished. or you can send me some data, I am happy to debug it with this data.

**Comment by biozhangzhou** [comment]
Thank you very much. I will try let it running for more time. Otherwise I will send you the data.
