### ISSUE TITLE
Unexplained status when I run

### ISSUE THREAD

**Issue by Weihankk** [Nextomics/NextDenovo#73]
Hi, yesterday I used NextDenovo v2.3.0 to assemble my Pacbio data.  Everything is fine at the beginning. But  after **ctg_algin** it seems stop without any information. I can found some process by **ps**,  and some **ctg_cns.py** process show status **S+**. 

I suspect it is a problem with my computer, so I tried two times in different node. Unfortunately, both of them showed the same  problem.  What's even stranger is that in my seconde test in another node it cause many zombie process (**status : Z** ). 

Here are screenshots of my problem:
----------------------------------
The first time I tried on my node2, it has 256G RAM and 40 threads, disk space is enough to store the process files. 
I run this task in three days ago. When I found it seems stop so I uss ctrl+C to stop it.  Now I find some zombie process.
![image](https://user-images.githubusercontent.com/33243134/86204074-2ac27980-bb99-11ea-8992-32ffd1c19109.png)

----------------------------------
Yesterday morning I trid the second time to run it. I change to node3, it has 512G RAM and 88 threads. 
It seems stop now:
![image](https://user-images.githubusercontent.com/33243134/86204297-bd631880-bb99-11ea-946e-86aa7db8ef66.png)

Many **ctg_cns.py** process showed **S+**
![image](https://user-images.githubusercontent.com/33243134/86204479-306c8f00-bb9a-11ea-8163-532da3d52c64.png)

RAM is not used.
![image](https://user-images.githubusercontent.com/33243134/86204547-5e51d380-bb9a-11ea-9ccd-fdd6d46737b4.png)

**top** command showed no process, either.
![image](https://user-images.githubusercontent.com/33243134/86204569-6e69b300-bb9a-11ea-9ccf-3ce754024324.png)

---------------------------------
Here is my run.cfg.
![image](https://user-images.githubusercontent.com/33243134/86204680-ac66d700-bb9a-11ea-8beb-ea4e7682c954.png)

In addition, the genome size I assemble is about 250MB, a plant.  I input two fasta format file , about 130X pacbio data. 

Thank for your help. If you need additional information or testing, please contact me.

**Comment by moold** [comment]
1. change `-x ava-ont` to `-x ava-pb` if you used the PacBio data.
2. change `pa_correction` to 3.

**Comment by Weihankk** [comment]
Thank you. It's running correctly now.
