### ISSUE TITLE
nextdenovo correct pacbio subreads

### ISSUE THREAD

**Issue by licheng0921** [Nextomics/NextDenovo#75]
Hi, 
I tried to correct pacbio raw date with nextdenovo. 
I find that only ~20x reads left, it is normal?
whether should I set seed cutoff shorter?

ps:
the genome is ~7.4g, raw subreads = 590g(~80x)
seed cutoff is calculated by seq_stat.

**Comment by moold** [comment]
Yes, if you need more corrected data. Try to set `correction_options = -b -p 10`  and  remove file `workdir/02.cns_align/01.seed_cns.sh.done` and `work/02.cns_align/01.seed_cns.sh.work/seed_cns*/nextDenovo.sh.done`, and rerun your main script. It will skip corrected seeds and only correct filtered seeds.

**Comment by licheng0921** [comment]
Thank you very much. I will do it as you advised.

**Comment by licheng0921** [comment]
Sorry to bother you again.
I checked others comments about `correction_options = -b -p 10`.
I do not know whether my understanding right or not.
If I continue assemble using nextdenovo, I have no need to add `-b` to rerun?
If I assemble the genome using other assembler, like: wtdbg2 or flye, I should rerun the main script with `correction_options = -b -p 10`?

many thank!

**Comment by moold** [comment]
yes

**Comment by licheng0921** [comment]
yes, I will try correct subreads using nextdenovo.
thanks to remined me.
