### ISSUE TITLE
What do contig types 'junction' and 'breakpoint' mean?

### ISSUE THREAD

**Issue by zhangrengang** [Nextomics/NextDenovo#80]
**Question or Expected behavior**
In the final `nd.asm.fasta`, there are four types (or more?): linear, loop, junction and breakpoint. Among these, linear and loop is easy to understand, but how to understand junction and breakpoint?

**NextDenovo**
2.3.0

**Comment by moold** [comment]
Hi, breakpoint means a node/read without outdegree (a path can not be extended),  junction means a node/read with >1 indegree and >1 outdegree (a path does not know how to be extended).
