### ISSUE TITLE
version `GLIBC_2.14' not found

### ISSUE THREAD

**Issue by unique379** [Nextomics/NextDenovo#81]
Hi
I downloaded the package as suggested and i guess its already precomplied version as i was able to run NExtDenovo excutable and make was not present. But While running the pipeline GLIB errors found for numerous depended packages such as seq_dump:
 “/lib64/libc.so.6: version `GLIBC_2.14' not found (required by /softwares/NextDenovo/bin/seq_dump)”

Please provide me the source code or working recompiled version of the tool. i dont find in github as source have only doc zipped.

Thank
Rupesh

**Comment by moold** [comment]
Pls provide more information

**Operating system**
Which operating system and version are you using?
You can use the command `lsb_release -a` to get it.

**GCC**
What version of GCC are you using?
You can use the command `gcc -v` to get it.

**Python**
What version of Python are you using?
You can use the command `python --version` to get it.

**NextDenovo**
What version of NextDenovo are you using?
You can use the command `nextDenovo -v` to get it.

**Comment by unique379** [comment]
Hi
here are your answers:

**OS:**
```
LSB Version:	:base-4.0-amd64:base-4.0-noarch:core-4.0-amd64:core-4.0-noarch:graphics-4.0-amd64:graphics-4.0-noarch:printing-4.0-amd64:printing-4.0-noarch
Distributor ID:	CentOS
Description:	CentOS release 6.7 (Final)
Release:	6.7
Codename:	Final
```

**GCC:**
`gcc version 4.4.7 20120313 (Red Hat 4.4.7-16) (GCC)`

**Python:**
`Python 3.7.7`

**NextDenovo**
`nextDenovo v2.3.0`

**ERRORS:**

```
bin/seq_dump --help

bin/seq_dump: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by bin/seq_dump)

bin/bam_sort --help

bin/bam_sort: error while loading shared libraries: liblzma.so.5: cannot open shared object file: No such file or directory

```

**Comment by moold** [comment]
Hi, your system and gcc are too old. I have recompile a version using gcc version 4.4.7, you can download 
[NextDenovo.tar.gz](https://github.com/Nextomics/NextDenovo/files/5032901/NextDenovo.tar.gz) and try again.

**Comment by unique379** [comment]
Thank you so much for providing the right precomplied version, its working for my system now.
by the way, i ran stats (by following the tutorial; https://github.com/Nextomics/NextDenovo/blob/master/doc/TEST1.md) on my ONT fastq but tool suggested no seed ? what do you think about this situation ?

[```
Read length stat]
Types            Count (#) Length (bp)
N10                 400130   20662
N20                1058422   15036
N30                1889004   12464
N40                2874343   10612
N50                4028581    9052
N60                5393149    7564
N70                7065565    6001
N80                9264517    4358
N90               12421838    2914

Types               Count (#)           Bases (bp)  Depth (X)
Raw                  21760220         115154951711      38.38
Filtered              3266343           2071372757       0.69
Clean                18493877         113083578954      37.69

*Suggested length cutoff of reads (genome size: 3000000000, expected seed depth: 45) to be corrected: 0 bp
```

**Comment by moold** [comment]
your data is not enough。
