### ISSUE TITLE
Pulling corrected long reads with v2.3.0

### ISSUE THREAD

**Issue by KevinBredemeyer** [Nextomics/NextDenovo#82]
Hello,
I was wondering how to go about pulling reads corrected by NextDenovo v2.3.0?
When I was running v2.2-beta I used the following command:
$ cat nextdenovo-OUT/02.cns_align/01.get_cns.sh.work/get_cns*/cns.fasta > next.correctedReads.fasta

But it appears naming/location of the corrected reads has been changed in the most recent version. 

Running on linux with python v3.7.4

Thanks!

**Comment by moold** [comment]
Hi, you can check the log file named `pidXXX.log.info`, it will tell you the corrected reads  are located at `work_dir/02.cns_align/01.seed_cns.sh.work/seed_cns*/cns.fasta`

**Comment by KevinBredemeyer** [comment]
Great, thank you!
