### ISSUE TITLE
too many step to run

### ISSUE THREAD

**Issue by longzhangnation** [Nextomics/NextDenovo#84]
I am using nextDenovo to correct my nanopore reads , but I find about total 1600 nextDenovo.sh under `01_rundir/01.raw_align/02.raw_align.sh.work/raw_align*` , as I estimate , it should take over 60 days to finish correction . Do you have any good idea to accelerate it ?

**Comment by moold** [comment]
see FAQ III and IV

**Comment by longzhangnation** [comment]
OK . Thank you .
