### ISSUE TITLE
“stop” at the cns_align step

### ISSUE THREAD

**Issue by WenhaoLiu0218** [Nextomics/NextDenovo#87]
Dear authors,
i used nextdenovo to run genome assembly (the genome size is about 1GB, raw data size is about 100G), it looks like "stopping" at the cns_align step, since the file (cns.filt.dovt.ovl and cns.filt.dovt.ovl.bl) in 01_rundir/02.cns_align/02.cns_align.sh.work/cns_align* is still keep empty, however, the software has been ran this step for 5 days with the CPU time keep increscing. The same issue occured when i changed to the older version. I don't know what is the problem for it, not enough CPU to run it (i use 10 CPU cores to run it and the SGE monitor shows the vmem is always keep at about 500G) or for some other reasons?
it would be very appreciate if i can get your help! 

here is my run.cfg:
[General]
job_type = local
job_prefix = nextDenovo
task = all # 'all', 'correct', 'assemble'
rewrite = yes # yes/no
deltmp = yes
rerun = 3
parallel_jobs = 20
input_type = raw
input_fofn = input.fofn
workdir = 01_rundir
[correct_option]
read_cutoff = 1k
seed_cutoff = 9k (the result of bin/seq_stat, conf: -g 1GB, -d 50)
blocksize = 2g
pa_correction = 20
seed_cutfiles = 20
sort_options = -m 20g -t 10 -k 50
minimap2_options_raw = -x ava-pb -t 8
correction_options = -p 15
[assemble_option]
minimap2_options_cns = -x ava-pb -t 8 -k17 -w17
nextgraph_options = -a 1
 
and the end of the nextDenovo.sh.e file in cns_align000:
[M::mm_idx_gen::51.103*1.14] collected minimizers
[M::mm_idx_gen::62.541*1.16] sorted minimizers
[M::main::62.541*1.16] loaded/built the index for 57675 target sequence(s)
[M::mm_mapopt_update::63.031*1.16] mid_occ = 2742
[M::mm_idx_stat] kmer size: 17; skip: 17; is_hpc: 1; #seq: 57675
[M::mm_idx_stat::63.336*1.15] distinct minimizers: 11002036 (26.52% are singletons); average occurrences: 8.938; average spacing: 11.761

**GCC**
What version of GCC are you using?
7.4.0 (GCC)

**Python**
What version of Python are you using?
2.7.9

**NextDenovo**
What version of NextDenovo are you using?
v2.3.0

**Comment by moold** [comment]
Try `minimap2_options_cns = -x ava-pb -t 8 -k17 -w17 --mode 1`

**Comment by WenhaoLiu0218** [comment]
Hi,
Thanks for your reply to our question, we added the parameter "--mode 1" which change the slow mode to fast mode, but the file is still empty for about 5 days.

**Comment by moold** [comment]
Could you share the two input files with me? I need  the input files to check what happened?

**Comment by WenhaoLiu0218** [comment]
Sorry for applying late, finally, we spend about 1.5 months to run this step, so it's just very slow. We have already finished the final assembly, thanks very much!
