### ISSUE TITLE
How to check random_round results in Nextdenovo v2.3.1

### ISSUE THREAD

**Issue by LeoCao-X** [Nextomics/NextDenovo#88]
**Question or Expected behavior**
In the old version, NextDenovo will save random assembly results in 03.ctg_graph/03.ctg_cns.sh.work directory. But in the newest version, I set random_round=20 in run.cfg but there are just 7 results in 03.ctg_graph/03.ctg_cns.sh.work directory. Is that normal in the newest version? How to check other random assembly results.
This is intact run.cfg I use:
[General]
job_type = local
job_prefix = nextDenovo_20200915_V1
task = all # 'all', 'correct', 'assemble'
rewrite = yes # yes/no
deltmp = yes
rerun = 3
parallel_jobs = 20
input_type = raw
input_fofn = ./input.fofn
workdir = ./20200915_V1_repeat

[correct_option]
read_cutoff = 2k
seed_cutoff = 26084
blocksize = 3g
pa_correction = 6
seed_cutfiles = 8
sort_options = -m 200g -t 10 -k 45
minimap2_options_raw = -x ava-ont -t 10
correction_options = -p 10 

[assemble_option]
random_round = 20
minimap2_options_cns = -x ava-ont -t 6 -k17 -w17
nextgraph_options = -a 1

**Operating system**
4.14.65-gentoo

**GCC**
What version of GCC are you using?
gcc version 7.3.0 (Gentoo 7.3.0-r3 p1.4)
**Python**
What version of Python are you using?
Python 3.8.3

**NextDenovo**
What version of NextDenovo are you using?
Nextdenovo v2.3.1

**Additional context** (Optional)

**Comment by moold** [comment]
The new version doest not support random options, because the random results have more errors than the default one, and most of users do not known how to chose result and just select the one with longest N50.

**Comment by LeoCao-X** [comment]
Thanks so much.
