### ISSUE TITLE
python3 ? 

### ISSUE THREAD

**Issue by colindaven** [Nextomics/NextDenovo#9]
Interesting software, but python2 ? End of life in less than 6 months ?

Is a port to python3 in progress ?

cheers!

**Comment by moold** [comment]
Hi, thank you for your suggestion. Currently, I have no plan to move it to Python3, since the core code is implemented with C and Python is used as a "glue" language.

**Comment by colindaven** [comment]
Thanks. Bit worried about how python2 programs are going to be supported or function at all after 2020 on our Ubuntu 1604 cluster. Will upgrade in summer 2020 to the next LTS

**Comment by moold** [comment]
This may be a questions for others as well and I will re-consider your suggestions. Thanks.

**Comment by chunlinxiao** [comment]
our systems no longer support python2  - hopefully you can move this tool to python3 sooner.
