### ISSUE TITLE
ctg_align aborting

### ISSUE THREAD

**Issue by fengyuanli304** [Nextomics/NextDenovo#90]
Hi, I run nextdenovo2.3.0 a few days, and I meet the following error:

[ERROR] 2020-10-13 07:12:59,063 ctg_align failed: please check the following logs:
[ERROR] 2020-10-13 07:12:59,075 /lustre2/nextdenovonewresult/03.ctg_graph/02.ctg_align.sh.work/ctg_align5/nextDenovo2.3.0.sh.e

the wrong file (nextDenovo2.3.0.sh.e):

hostname

    hostname
    cd /lustre2/nextdenovonewresult/03.ctg_graph/02.ctg_align.sh.work/ctg_align5
    cd /lustre2/nextdenovonewresult/03.ctg_graph/02.ctg_align.sh.work/ctg_align5
    time /lustre2/software/NextDenovo/bin/minimap2-nd -x map-pb -a -t 18 /lustre2/nextdenovonewresult/03.ctg_graph/01.ctg_graph.sh.work/ctg_graph0/nd.asm.p.fasta /lustre2/nextdenovonewresult/.//01.raw_align/input.seed.005.2bit|/lustre2/software/NextDenovo/bin/bam_sort -i -@ 18 -o input.seed.005.2bit.sort.bam
    /lustre2/software/NextDenovo/bin/minimap2-nd -x map-pb -a -t 18 /lustre2/nextdenovonewresult/03.ctg_graph/01.ctg_graph.sh.work/ctg_graph0/nd.asm.p.fasta /lustre2/nextdenovonewresult/.//01.raw_align/input.seed.005.2bit
    /lustre2/software/NextDenovo/bin/bam_sort -i -@ 18 -o input.seed.005.2bit.sort.bam
    [M::mm_idx_gen::74.0331.76] collected minimizers
    [M::mm_idx_gen::98.8371.99] sorted minimizers
    [M::main::98.8381.99] loaded/built the index for 1084 target sequence(s)
    [M::mm_mapopt_update::103.1241.95] mid_occ = 1322
    [M::mm_idx_stat] kmer size: 19; skip: 10; is_hpc: 1; #seq: 1084
    [M::mm_idx_stat::104.2571.94] distinct minimizers: 68259648 (45.72% are singletons); average occurrences: 6.155; average spacing: 8.329
    [M::worker_pipeline::564.5245.46] mapped 9336 sequences
    [M::worker_pipeline::1002.5955.80] mapped 9334 sequences
    [M::worker_pipeline::1457.2465.93] mapped 9373 sequences
    [M::worker_pipeline::1879.4736.03] mapped 9399 sequences
    [M::worker_pipeline::2276.0416.18] mapped 9358 sequences
    [M::worker_pipeline::2719.1116.14] mapped 9294 sequences
    [M::worker_pipeline::3162.7256.09] mapped 9404 sequences
    [M::worker_pipeline::3570.6946.10] mapped 9345 sequences
    [M::worker_pipeline::4011.6326.10] mapped 9290 sequences
    [M::worker_pipeline::4471.0936.09] mapped 9342 sequences
    [M::worker_pipeline::4882.3066.15] mapped 9379 sequences
    [M::worker_pipeline::5339.2726.12] mapped 9401 sequences
    [M::worker_pipeline::5857.4836.06] mapped 9373 sequences
    [M::worker_pipeline::6284.6736.06] mapped 9369 sequences
    [M::worker_pipeline::6724.0656.05] mapped 9394 sequences
    [M::worker_pipeline::7264.340*6.04] mapped 9409 sequences
    [W::sam_read1] Parse error at line 1334846
    samtools sort: truncated file. Aborting

Genome characteristics
genome size: 2.9G, heterozygous rate: 1.30%, repeat content: 60.05%

Input data
Total base count 244,238,273,438 bp, sequencing depth 84, average/N50 read length 37,906

Operating system
Which operating system and version are you using?
CentOS Linux relase 7.6.1810

GCC
What version of GCC are you using?
4.8.5 20150623 (Red Hat 4.8.5-36)

Python
What version of Python are you using?
python2.7.18

NextDenovo
What version of NextDenovo are you using?
nextdenovo2.3.0

[General]
job_type = local
job_prefix = nextDenovo2.3.0
task = all # 'all', 'correct', 'assemble'
rewrite = yes # yes/no
deltmp = yes
rerun = 3
parallel_jobs = 8
input_type = raw
input_fofn = ./input.fofn
workdir = ./

[correct_option]
read_cutoff = 1k
seed_cutoff = 36k
blocksize = 3g
pa_correction = 4
seed_cutfiles = 4
sort_options = -m 80g -t 25 -k 45
minimap2_options_raw = -x ava-pb -t 12
correction_options = -p 20

[assemble_option]
minimap2_options_cns = -x ava-pb -t 12 -k17 -w17
nextgraph_options = -a 1

Can you help me to figure out how to solve it? Thank you.

**Comment by moold** [comment]
Hi, could you try to run the following command manually?
```
/lustre2/software/NextDenovo/bin/minimap2-nd -x map-pb -a -t 18 /lustre2/nextdenovonewresult/03.ctg_graph/01.ctg_graph.sh.work/ctg_graph0/nd.asm.p.fasta /lustre2/nextdenovonewresult/.//01.raw_align/input.seed.005.2bit -o input.seed.005.2bit.sam
/lustre2/software/NextDenovo/bin/bam_sort -i -@ 18 -o input.seed.005.2bit.sort.bam input.seed.005.2bit.sam
```

**Comment by fengyuanli304** [comment]
Thanks a lot.
