### ISSUE TITLE
 assembly graph

### ISSUE THREAD

**Issue by heziqing** [Nextomics/NextDenovo#93]
Dear Dr. Hu，
**Describe the bug**
I want to use the assembly graph to run SALSA ( A tool to scaffold long read assemblies with Hi-C), so I change the nextgraph_options= -a 3, not -a 1. But I meet an error, as follows. I had run the nextDenovo successfully before with the nextgraph_options= -a 1 before.

**Error message**
Traceback (most recent call last):
  File "/share/home/heziqing/NextDenovo2.3.1/nextDenovo", line 783, in <module>
    main(args)
  File "/share/home/heziqing/NextDenovo2.3.1/nextDenovo", line 754, in main
    asm, stat = gather_ctg_cns_output(cfg, task.subtasks, seq_info)
  File "/share/home/heziqing/NextDenovo2.3.1/nextDenovo", line 278, in gather_ctg_cns_output
    out = cal_n50_info(stat, asm + '.stat')
  File "/share/home/heziqing/NextDenovo2.3.1/lib/kit.py", line 171, in cal_n50_info
    out += "%-5s %18d%20s\n" % ("Min.", stat[-1], '-')
IndexError: list index out of range

thanks in advance!

**Comment by moold** [comment]
Hi, NextDenovo does not support outputting the final result in GFA2 format, while it can output the intermediate result in GFA2 format. You can change to `03.ctg_graph/01.ctg_graph.sh.work/ctg_graph0` directory, and run `-a 1` to get fasta file and run `-a 3` to get GFA2 file. This result file has some differences with the final result and may contain more errors.

**Comment by heziqing** [comment]
ok, thanks!
