### ISSUE TITLE
the question about nd.asm.p.fasta

### ISSUE THREAD

**Issue by WenhaoLiu0218** [Nextomics/NextDenovo#96]
Dear author，

i finished the final assembly using NextDenovo (v2.3.0). I found the file nd.asm.p.fasta in 01.ctg_graph.sh.work/ctg_graph0,    my question is what's the difference between this file and the final assembly result nd.asm.fasta. By using the old version, i can get some assembly results and choose the best one through them, but i could not find these files in the new version, and the N50 length of nd.asm.p.fasta is longer than N50 of nd.asm.fasta, although the BUSCO result is a little bit low, i wonder whether i can chose nd.asm.p.fasta as the final assembly result or not? Thanks!

**Comment by moold** [comment]
1. In theroy, `nd.asm.p.fasta`  contains more structural & base errors than `nd.asm.fasta`, you also can chose `nd.asm.p.fasta` as the final assembly result, but be careful about the assembly quality.
2. Too many users complained that they didn't know how to choose the assembly result, so I removed this function, you can change the assembly parameters in `nextgraph_options` manually, and rerun it. NextDenovo will skip the previous steps and only run the last step.

**Comment by WenhaoLiu0218** [comment]
Thanks for replying! I will try to change assembly parameters.

**Comment by Barbossa-V** [comment]
Dear author，
I try to assemble some scafolds from metagemomic. The file 'input.fofn' contain three fasta-format file.  But I 've failed in the 'assemble 'step when using ’nextgraph‘.  I 've found that the nd.asm.p.fastq file is [null]! But the  input file for nextgraph is normal, including '01.ctg_graph.input.seqs'  and '01.ctg_graph.input.ovls' . How can I adjust parameters of 'nextgraph',  can you give me some suggest ，please ？ Thank you very much.

**Comment by moold** [comment]
NextDenovo is not suitabale for metagemomic, because it assumes the genome has a uniform depth of coverage. But if you still want to have a  try, you can set `seed_cutoff=1000`. 
Besides, I will close this issue, if you still have problem, you need to open a new issue because your question is not related to this issue.

**Comment by Barbossa-V** [comment]
Thank you very much! my parameters are： read_cutoff = 0.2k ，genome_size = 100g，seed_depth = 1，seed_cutoff = 3k，blocksize = 1g，minimap2_options_raw = -x ava-pb --minlen 20 --minmatch 20 -x ava-pb -t 4，nextgraph_options = -a 1 -E 200
