### ISSUE TITLE
ARM support

### ISSUE THREAD

**Issue by q623928815** [Nextomics/NextDenovo#97]
**Question or Expected behavior**
A clear and concise description of your question or what you expected to happen.
ARM support or provide source code

**Operating system**
Which operating system and version are you using?
You can use the command `lsb_release -a` to get it.
armv8 and centos7.9

I want to transplant it to arm, butt here are no source code to: bam_sort   nextgraph  ovl_cvt  ovl_sort  seq_bit  seq_dump  seq_stat
Can you publish it or build an ARM version? Thanks

**Comment by moold** [comment]
I have released a version that supports ARM, you can try it in the release page.
