### ISSUE TITLE
How can I get more information of the random assembly nd.asm.p.fasta ? 

### ISSUE THREAD

**Issue by tinyhys** [Nextomics/NextDenovo#99]
Dear doctor ,
Thanks to provide such an excellent tool for long reads assembly!
I have accomplished  several plant genome assembly using ONT data  with the help of NextDenovo and NextPolish and spent some time on optimizing the configs. However, I found that no matter how I adjusted the config options, the N50 value of nd.asm.p.fasta was always larger than the nd.asm.fasta with fewer contig count.
I have read the issue 96 (<https://github.com/Nextomics/NextDenovo/issues/96>), but it also confused me. I want to know whether is the algorithm or the input configs or something else which causes the difference? If the configs for the assembly of nd.asm.p.fasta takes the responsibility, how can I get the configs ?
Any reply will be very grateful!
best wishes sincerely~

**Comment by moold** [comment]
No, the `nd.asm.p.fasta` is just an intermediate result, so I do not recommend using it.

**Comment by tinyhys** [comment]
> No, the `nd.asm.p.fasta` is just an intermediate result, so I do not recommend using it.

thanks for your recommend, I will use the `nd.asm.fasta` file to do the following analysis~
